### ISSUE TITLE
Patient search on the central server

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#1061]
- [ ] implement patient search api (work in progress: https://github.com/openmsupply/open-msupply/tree/1061-patient-search-api) 
- [ ] integrate central search (in local search + UI changes)

**Comment by nisha-dangol** [comment]
Hi @clemens-msupply 
Checked/Tested this on v1.3.00.
1. I've two oms-sites set up. Created Patient1 in site1 and synced.
2. In site2, created new patient with same details as of Patient1
3. Instead of showing `Patient found` window, it lets me create new patient entry instead. See [recording here](https://recordit.co/DX2kE9Oib2).
Central search is not working in v1.3.00! (Have also checked this on both desktop exe and mobile apk)

**Comment by clemens-msupply** [comment]
Might be the birthday, does it find the patient if you just enter a name? e.g. just the firstName.

**Comment by nisha-dangol** [comment]
> Might be the birthday, does it find the patient if you just enter a name? e.g. just the firstName.
>
To answer your question, yes it seems to work that way, but the same doesn't work if I'm to enter the date at first, then remove it again so that the date field is now empty and only firstName is populated. Kinda bug? See [recording for reference!](https://recordit.co/rmRner3KmS) 

And, another quick questions please:
1. Is it expected that the search won't trigger if the name (first or last) contains existing names in other oms-sites. For eg: `site2` has a patient name, let's say `patient2` and if I'm to search the term `pat` (not the whole name) from `site1`, shouldn't it show up the names containing the search term `pat`? 
2. RN, the search is triggered only by first or last names, but shouldn't it consider the NID/Patient Code as well? Is it expected that multiple patients can share the same NID?

**Comment by clemens-msupply** [comment]
Thank you, could you please create an issue for it?

It looks like the patient is found on the central server. This search uses a different search endpoint from mSupply. I have the feeling that this endpoint only does an exact match, or it is use incorrectly on the omSupply side. Could you please add this to the issue as well?

> RN, the search is triggered only by first or last names, but shouldn't it consider the NID/Patient Code as well? Is it expected that multiple patients can share the same NID?

Please add to the issue as well, would have to investigate, it should consider the code for the central search.

**Comment by nisha-dangol** [comment]
> Thank you, could you please create an issue for it?
>
Sure, reported this bug: #2220 
<br><br>
> 
> It looks like the patient is found on the central server. This search uses a different search endpoint from mSupply. I have the feeling that this endpoint only does an exact match, or it is use incorrectly on the omSupply side. Could you please add this to the issue as well?
> > RN, the search is triggered only by first or last names, but shouldn't it consider the NID/Patient Code as well? Is it expected that multiple patients can share the same NID?
> Please add to the issue as well, would have to investigate, it should consider the code for the central search.
>
Done, this can be further discussed/investigated here: #2223
