### ISSUE TITLE
Item name disappears on `Add item` window in a stocktake

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#1082]
Placeholder issue from P & D - When editing an item in stocktake, the item name (in the item category) does not appear, meaning we are not sure which item is being edited once the menu is opened. *edit* this happens for all item dropdown menus, and if (after typing an item) 'Go' is clicked it resets the entire process (only in new inbound shipments)

**Comment by DhanyaHerath** [comment]
@Pauline-mSupply would you be able to add the screenshot for this here please?

**Comment by mark-prins** [comment]
This is what I'm seeing on the emulator when running the latest version ( my tablet is running android 8.1 and so doesn't support oms mobile 🙄 )
So, not sure what the issue is. Can you help me understand the problem please?

![Screenshot 2023-01-25 at 2 50 17 PM](https://user-images.githubusercontent.com/9192912/214462758-a2848eda-1c07-475c-922f-dbad4e770606.png)

![Screenshot 2023-01-25 at 2 50 31 PM](https://user-images.githubusercontent.com/9192912/214462762-92eeb185-a5da-4861-9e5c-8b57efaf2647.png)

![Screenshot 2023-01-25 at 2 49 41 PM](https://user-images.githubusercontent.com/9192912/214462749-5cc67cc1-f453-48a5-bc50-b692cfb002a2.png)

Sorry! the phrases in the description aren't matching with what I'm used to.. so am struggling a bit.

**Comment by Pauline-mSupply** [comment]
Hello team, 

I am new to Github so I am not sure this is the right place... (but very honoured). Here is a video of what it looks like : 

https://user-images.githubusercontent.com/114633283/214998830-10dfa6dd-b74c-4ce5-9d6a-4ed5b00b73ad.mp4

**Comment by Pauline-mSupply** [comment]
Hello you two, 

I am new to Github (but very honoured), I have added a video of the issue in Github, I hope it shows correctly for you !

Let me know

Cheers,

Pauline

Pauline Robert

The mSupply Foundation
105/55 Anzac Ave    |    Auckland 1010    |    New Zealand  
https://msupply.foundation <https://msupply.foundation/>
***@***.*** ***@***.***>

**Comment by mark-prins** [comment]
Thanks @Pauline-mSupply - came through perfectly!
The issue has been fixed already - are you able to upgrade to the latest version of the app? that will have the fix in it.

**Comment by DhanyaHerath** [comment]
@mark-prins I can't see the PR so I'm not sure what the fix was, but it seems like it's missing in 1.1.4? I'm back to being unable to see the item name

![image](https://user-images.githubusercontent.com/29744386/223619720-c042b9fc-6609-45ed-8143-de26af29448e.png)

**Comment by mark-prins** [comment]
Perhaps scroll up? In the screenshot, the entire item area appears to be missing, which is not the issue that I was saying was fixed. The problem I was referring to was a hard limit on the number of items returned by the API - this meant that the stocktake line had an item id - but the modal was unable to display the name of the item, because the list of items was incomplete.

As a comparison - this is what the edit item modal looks like when there is more screen size available:

<img width="792" alt="Screenshot 2023-03-08 at 5 45 49 PM" src="https://user-images.githubusercontent.com/9192912/223621956-e849f463-0539-4cdb-aedd-aab456f6c247.png">

**Comment by DhanyaHerath** [comment]
Ah fair enough @mark-prins! I thought the initial solution had been to add the item name to the header. I think it would still be helpful to be able to see, particularly when click OK/Next to go through the items, but this is minor then, I can close.
