### ISSUE TITLE
Incorrect authentication error notification (f/e)

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#109]
Just something I've noticed lately -- I keep getting the "Timed out" message even when it should be just a regular unauthenticated error.

If I restart the server and refresh the page, I get the following, even though you can see the server is returning "Unauthenticated":
<img width="1390" alt="Screen Shot 2022-06-09 at 11 17 16 AM" src="https://user-images.githubusercontent.com/5456533/172733214-0c6e6a49-a98e-4d4c-b8e1-cef1c540ed71.png">

**Comment by mark-prins** [comment]
that could be interesting to work through. we only know that users are 'unauthenticated' and aren't tracking the distinction between 'previously authenticated but not now' and 'just plain not logged in' so I went with a message that covered the most likely scenario.

when the cookie expires it disappears - though we will have existing state to refer to, so perhaps could use that to determine 'timed out' rather than 'unauthenticated'. Essentially switching around the default message to be 'not logged in' and add another state for timed out. would that work?

**Comment by jmbrunskill** [comment]
That sound good to me Mark, I also find this 'incorrect' error message annoying even though it's less likely to happen in production.

We are probably seeing this a lot in dev, as the server doesn't persist authentication tokens, so whenever you restart the server you'll need to re-authenticate. Another ticket/issue could be to somehow persist the tokens server side, so that you aren't logged out on a restart. This would mainly help dev, but would be nice for production as well I think.

**Comment by CarlosNZ** [comment]
Yeah, makes sense for the default to be "not logged in" rather than "timed out".

There's two different routines for checking Login errors and Timeouts, but they both give `AuthError.Unauthenticated` error, so we can just make a separate `AuthError.Timeout` that can be set by the timeout check instead?

**Comment by CarlosNZ** [comment]
> There's two different routines for checking Login errors and Timeouts, but they both give `AuthError.Unauthenticated` error, so we can just make a separate `AuthError.Timeout` that can be set by the timeout check instead?

I'll try this quickly now, @mark-prins . If it turns out to be more complicated than the quick fix it looks like, I'll leave it.
