### ISSUE TITLE
Pregnancy section should only be enabled if patient is female

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1236]

**Comment by CarlosNZ** [comment]
Which form schema is this for @roxy-dao ?

**Comment by roxy-dao** [comment]
HIV Care Encounter

**Comment by CarlosNZ** [comment]
Leave as is for now.

**Comment by clemens-msupply** [comment]
This would require having the patient data available in the care encounter form. While this is a reasonable thing to have we also need to have something like a custom or extended group control which can have rules that operate on the patient data. These rules could have the same syntax and behaviour as the JSONForms rules but work on the patient data instead of the form data.

@richardmoizeau this is reasonable complex with only little UX improvements (?), e.g. clinician should know if the section is applicable or not. What do you think we should close this issue or keep it in the backlog?

**Comment by clemens-msupply** [comment]
@richardmoizeau can this be closed?

**Comment by richardmoizeau** [comment]
yes
