### ISSUE TITLE
Programs: Viral Load Eligibility report - missing data

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1354]
## What went wrong? 😲
 

![IMAGE 2023-03-15 12:44:33](https://user-images.githubusercontent.com/74992958/225166438-1252cfdf-be38-4cf6-b2e5-dae96103677c.jpg)

## Expected behaviour 🤔

showing the right data ;-) 

For Clara Johnson for instance, last VL date should be = 10/03/2022

## Your environment 🌱
 - Version 114
 - [Platform](https://demo-open.msupply.org:88/dispensary/reports?sort=name)

**Comment by clemens-msupply** [comment]
I updated the server to use the latest reports. You shouldn't really see anything in here till the patient is eligible for a VL though... (The report doesn't show why the patient is eligible though...)

We might have to fake some data to be far enough in the past to show the different statues? Also see:
https://github.com/openmsupply/open-msupply-reports/issues/15

**Comment by clemens-msupply** [comment]
BTW. The report are currently not showing anything because I filter for "Completed" encounters. I can remove this check though since its not something that is in the original HTDB...

**Comment by clemens-msupply** [comment]
I will remove the encounter status filter from the report (at least for now).

For testing it you can add encounters to a new patient  and schedule the encounter far enough into the past so that you can trigger the different conditions. (it needs to be a "new" patient without encounters because if you have already some newer encounters they may void the VL conditions you trying to trigger...)
