### ISSUE TITLE
Authorisation

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1372]
## Is your feature request related to a problem? Please describe 👀

References: mSupply [Remote authorisation](https://docs.msupply.org.nz/other_stuff:remote_authorisation) and [Authorisation](https://docs.msupply.org.nz/other_stuff:invoice_authorization)

The authorisation relates only to customer requisitions but is completed via the standard omSupply app.

From the client proposal / requirements:
- A program order is sent (submitted) by a health facility to a supplier store - one will be available for each program.
- Authoriser can log into the central open mSupply instance - they will have access only to their store. Note: program orders that require an authorisation to appear first in the list.
- Authoriser can click on a program order to review order details: Item code, name and unit, Customer’s SOH, Customer‘s AMC, Target Stock, Suggested Quantity, Requested Quantity
- Authoriser can enter a new quantity that overrides the requested quantity entered by the customer.
- Authoriser can enter a comment at the order line level (for example, to provide clarifications if approved  quantity is different from the requested quantity)
- Once order is approved, customer will be able to see:
  - The quantity that has been approved in the new Approved Quantity column in the the order table
  - The comment that has been entered in order to clarify when the approved quantity is different from the requested quantity.
- Once an order is approved, the supplier will receive the order and can process it.

## Describe the solution you'd like 🎁
We have a complication, in that the TB program is going to be using omSupply, whereas all other stores will have stock come from the central warehouse, which is using SAGE.

The proposal is to use the remote authorisation process for the TB store; as this is a remote store, the authorisers are not able to log into it directly.

For the other programs, a store can be created for them which then syncs to a cloud hosted instance of omSupply. Authorisers can login to the cloud instance and modify the customer (response) requisition. When they are satisfied, they can change the approval status and finalise. 

Here's an attempt to visualise the process. 

[![](https://mermaid.ink/img/pako:eNqFU8tu2zAQ_JUFe3EA-1qgOjTwK46b-NE6hxaSUbDiyiYqkipJuTAi_3uWouzAbdDqIomcmeXODp9ZbgSyhO0sr_bwNMk00DNMv-CvGp2Xegcbbywm4MLrO9_CYPCxmWuPVvMSVlagbWCUZuxpFDHQM8rdZGwbtUaBAM2w9kZxL3NelkfILXKPooFxW0k66aXRHWMcGRvPfe0SWOJv4D85jI0upFWBNU0LnhR8gPqApakQlsbL4gi8qqw5oHWdkqt_xMao-t5Y6XgoA2trcnQuYsIzbSvepZ1s7dDCeM_1Dh0oLnC7fcXetdhZGlsARUJ8h38B7p-H8TDi9hT3UIv4MYv91ZUIAva1_2YcAfcR8A1dM-9lLG9PQuYGP6CnuK7J-So2QUbfXLGWphnFhXmSJB243SkkTUy6YOAnkh3HBlabtyQv1Ex3kYgafw7-gQZPdpLLCr62k-9CQDbnpalFCELgR5WHf4bh8Y0wPLaMRZqeR0ijKc3OgdTgDYSCbR36J4N0fpnVoiUuSfIgKUEHXlKg-6CMoKT0gQsBuVEKtT-nZdkyVsGa6Di_Ss3mP_6vru1ep-lmOJuej7NuFz-n6cX22_NWXnLnJlhAxy5kWSbvig_vWZ8ptIpLQTf0OYAz5veoMGMJfQoseF36jGX6RFA6rdkcdc4Sb2vss5ivieRhOIxyXTpaRSFpPot469vLf3oBqT5N7Q?type=png)](https://mermaid.live/edit#pako:eNqFU8tu2zAQ_JUFe3EA-1qgOjTwK46b-NE6hxaSUbDiyiYqkipJuTAi_3uWouzAbdDqIomcmeXODp9ZbgSyhO0sr_bwNMk00DNMv-CvGp2Xegcbbywm4MLrO9_CYPCxmWuPVvMSVlagbWCUZuxpFDHQM8rdZGwbtUaBAM2w9kZxL3NelkfILXKPooFxW0k66aXRHWMcGRvPfe0SWOJv4D85jI0upFWBNU0LnhR8gPqApakQlsbL4gi8qqw5oHWdkqt_xMao-t5Y6XgoA2trcnQuYsIzbSvepZ1s7dDCeM_1Dh0oLnC7fcXetdhZGlsARUJ8h38B7p-H8TDi9hT3UIv4MYv91ZUIAva1_2YcAfcR8A1dM-9lLG9PQuYGP6CnuK7J-So2QUbfXLGWphnFhXmSJB243SkkTUy6YOAnkh3HBlabtyQv1Ex3kYgafw7-gQZPdpLLCr62k-9CQDbnpalFCELgR5WHf4bh8Y0wPLaMRZqeR0ijKc3OgdTgDYSCbR36J4N0fpnVoiUuSfIgKUEHXlKg-6CMoKT0gQsBuVEKtT-nZdkyVsGa6Di_Ss3mP_6vru1ep-lmOJuej7NuFz-n6cX22_NWXnLnJlhAxy5kWSbvig_vWZ8ptIpLQTf0OYAz5veoMGMJfQoseF36jGX6RFA6rdkcdc4Sb2vss5ivieRhOIxyXTpaRSFpPot469vLf3oBqT5N7Q)

This does mean that the 'other program' outbound shipments will be from 'program x' to 'store_a'. Actual stock comes from the central warehouse.

Is this ok? 

Would also be good to have a log entry made for each field of the customer requisition which has values changed. Wondering about making the 'approved quantity' field editable for approvers to enable capture of this data.

An alternative would be to use the remote authorisation process for all programs.
This would require customer requisitions to be finalised and the outbound shipment created within omSupply, while the authorisation tasks are web/central. I don't think the split is ideal.

### Tasks required

- Check the `Use remote authorisation for response requisitions` store preference to see if the feature is enabled #1418 
- Check the `Include requisitions from this store in suppliers' remote authorisation processes` store preference to see if a customer requisition requires authorisation #1418 
- Create the `authoriser` table (id, user_id, is_active, list_master_id) #1418 
- Add `authoriser` to sync #1418 
- Change default ordering of requisitions in list view #1427
- Add an `Authorised` checkbox to customer requisitions  #1427. This is only enabled if
  - the requisition status is New, AND
  - authorisation is enabled for this store, AND
  - the current user is an authoriser of requisitions, AND
  - the current requisition has items which are in a master list that the authoriser is configured to use
- The requisition cannot be finalised if: 
  - the requisition is not authorised, AND
  - authorisation is enabled for this store, AND
  - the current requisition has items which are in a master list that the authoriser is configured to use
- When the above conditions are true, and the user clicks finalise, a prompt is shown telling the user that only authorised requisitions can be finalised #1427
- handle messages returned by central server #1450
- add approved quantity and authoriser comment to the customer requisition (unsure

### Issues
- [x] #1418 
- [x] #1450 
- [x] #1427 
- [x] #1425 

### Describe alternatives you've considered 💭
Contractual obligations 😉

**Comment by andreievg** [comment]
@mark-prins, are we replicating existing mSupply remote authorisation functionality ? 

How does [Authorisation](https://docs.msupply.org.nz/other_stuff:invoice_authorization#setting_up_authorisers) fit into this ? (they are separate functionality and I am not sure how we can do a combination of both?)

Authoriser will still be using the mSupply central server app ? (I got confused by this requirement: `Authoriser can log into the central open mSupply instance`)

We would need messages, authorisationQueue tables, processor for `messages` table, UI for authorisationQueue table, new status on requisition: https://wiki.sussol.net/doku.php/msupply:design:cambodia:authorisation_web_app?s[]=authorisation

**Comment by mark-prins** [comment]
> are we replicating existing mSupply remote authorisation functionality ?

As far as I can tell.. no. Not exactly. The requirements in the proposal have only a single authoriser required, not the current queue where multiple authorisers need to all approve. There's no requirement for authorisers to be emailed with a notification either.

There's also no request to have the authorisable items listed, like the remote auth does. We have a requirement to authorise response requisitions - which is more like the way that **Authorisation** works

> How does [Authorisation](https://docs.msupply.org.nz/other_stuff:invoice_authorization#setting_up_authorisers) fit into this ?

Which leads in to this question! My reading of the requirements is that we need **Authorisation**, but for response requisitions. Which is to say - you cannot finalise a response req without it being authorised. and the authorisation is for the whole requisition, not for lines.

> Authoriser will still be using the mSupply central server app

I thought that this is was an issue with wording of the requirement.. but now I'm worried! We'll have to check in with @richardmoizeau.. I thought the requirement is that users can log in to a web instance of omSupply which has the stores they need to authorise. I'm now not sure how this can work

**Comment by richardmoizeau** [comment]
> There's no requirement for authorisers to be emailed with a notification either.

> There's also no request to have the authorisable items listed, like the remote auth does. We have a requirement to authorise response requisitions - which is more like the way that Authorisation works

There are gonna be different authorisers for each national program (HIV, TB and Malaria). Non-program requisitions are not to be authorised at the central level. That's why i though this remote authorisation features would involve master lists.

**Comment by Chris-Petty** [comment]
This looks great! Just to be certain, the left side with the TB program is using the Remote Authorisation Web app?

> This does mean that the 'other program' outbound shipments will be from 'program x' to 'store_a'. Actual stock comes from the central warehouse. Is this OK?

At first thought, only rule being bent/broken would be within the Central Server integration with SAGE (needs desktop issue?). I imagine the approved requisition gets sent to SAGE, SAGE eventually creates an outbound shipment which is integrated into our central server. This requires the central server creating records owned by the Program X site; generally against the rules. But, not terribly far fetched as the central server also bends this rule when users use Remote Authorisation to edit approved quantity/comments on response requisition lines.

> Would also be good to have a log entry made for each field of the customer requisition which has values changed. Wondering about making the 'approved quantity' field editable for approvers to enable capture of this data.

![image](https://user-images.githubusercontent.com/7684221/229439943-09573552-815c-490b-833c-e448f0608f88.png)

The last pass at the remote authorisation module set out to capture these too! I reckon they'll be all good here too. I think you might need an mSupply desktop issue to create a condition that changes which series of events occurs though, least both authorisation processes are set off!

**Comment by andreievg** [comment]
I had a good look at public docs @mark-prins linked and also our [wiki docs](https://wiki.sussol.net/doku.php/msupply:design:remote_authorisation:customer_requirements:timor_leste?s[]=authorisation) describing how remote authorisation was implemented (or how it was changed from initial implementation). 

I also checked mSupply code base and this is what I've found:

* Authorisation is generated in response requisition when it's created [as a result of creating a transfer](https://github.com/sussol/msupply/blob/7bb36ea4e434af960109315dddfbcc9d91c05fb6/Project/Sources/Methods/requisition_create_response.4dm#L194-L199) (not when it's confirmed as per our public documentation):

* We don't actually change remote data via messages (i.e. remote response requisition is not updated via messages). As per the wiki docs, response requisition is temporary owned by central while it's being authorised, wiki wasn't clear what being authorised means, there is a diagram indicating "when all master lists involved in requisition are approved/denied. I clarified this after looking it up in code, it's determined by authorisationStatus = pending, this is set when [authorisationQueue is created](https://github.com/sussol/msupply/blob/7bb36ea4e434af960109315dddfbcc9d91c05fb6/Project/Sources/Methods/authorisationQueueCreate.4dm#L78-L79) and [editing is disabled in UI](https://github.com/sussol/msupply/blob/7bb36ea4e434af960109315dddfbcc9d91c05fb6/Project/Sources/Methods/requisition_disable_objects.4dm#L42-L44)

The above make it easy for use case where supplying store is active on primary (authorisation should be automatically generated when transfer is generate, so without any extra input), but makes it harder if supplying store is active on remote omSupply (since authorisation triggered when response requisition is generated as part of transfer).

If we want remote omSupply supplying site's response requisitions to be authorised, we would need to add logic to omSupply to:
* identify that created response requisition needs to go through authorisation:
    * checking shouldAuthoriseResponseRequisition preference in supplying store (the one active on the site doing the check)
    * checking that there is at least one authoriser configure to authorise this item (authorisers would need to sync, but there is already PR for this)
    * checking includeRequisitionsInSuppliersRemoteAuthorisationProcesses preference on the requesting store (afaik this is not possible currently, i think we only get preferences for stores that are active on site)
* trigger central server to generate authorisationQueue for this:
    * possibly by setting authorisationStatus to 'pending' 
    * central server logic to also authorisationQueueCreate when authorisationStatus is 'pending'
* disable editing requisition when authorisationStatus is pending (this still breaks sync rules, but if we need to do this quickly then this would be the way to go, we would have to allocate some time to revisit in the future)

**Authorisation by master list problem**

Looks like authorisations are created not quite by master list but by items in requisitions that match authoriser master list items, this means we cannot create authorisation by individual programs if there are shared items in the program master lists.

**Integrations with external systems**

I was going to mention, if we did end up solving remote authorisation for omSupply suppliers, it maybe good to think about SAGE integration with omSupply API (by making the central warehouse store a remote site, that lives on the same cloud server as central, maybe with very small sync interval)

**Conclusion**

I don't really have any concrete suggestions to offer at this hour, but I can see a number of challenges which put a spanner in the works, I think further discussion/design needs to be had, and I can't see how we can fit requirements without modifying central server functionality

**Comment by Chris-Petty** [comment]
> **Conclusion**
> 
> I don't really have any concrete suggestions to offer at this hour, but I can see a number of challenges which put a spanner in the works, I think further discussion/design needs to be had, and I can't see how we can fit requirements without modifying central server functionality

Me neither! Great sleuthing @andreievg. Adding context that because we added `requisition_line.approved_quantity`, which is edited through the central server webapp, creating messages to represent this data would have been quite the spaghetti for the REST API to build into responses - lines would have to take columns from both `requisition_line` and `message.payload.????` object fields. Opted to just bend the rules to get the last urgent authorisation project over the line 😉.

One alternative solution that you mentioned to me yesterday is creating separate _centrally owned_ tables that relate to the requisition/lines, so that the requisitions don't get edited by the central server and the webapp has something more robust to access. These could sync along with the requisition as _centrally owned store data_ too. This likely has legs but up to you if there's time. Keeping in mind to keep existing systems running fine, and it'd make the approval fields on requisition effectively de normalisations, if not just redundant.

Master list problem I was aware of, fair to have it work either way. One tweak would be that if a requisition has a `programID` set, then it's strictly authorisation by the master list related to that. So long as users only make "Program" requisitions and are limited to only adding items from that program it should be all good?

**Comment by andreievg** [comment]
@Chris-Petty, thanks for background, I think it's ok for now to have ownership temporary switched to central (as long as we are aware of this, and aim to improve it in the future). In fact it's not even a problem atm, the main problems afaik:
1. how to trigger authorisation on central
2. make sure we authorises by programId (masterList), rather then by item in a master_list

I was thinking maybe we can add a condition in sync v5, to check if sender and receiver require authorisation, and then create response requisition or central end rather then remote end, I think it would work, but I think it would still not deal with 2.

My current suggestion would be:

In omSupply, after creating transfer, check `shouldAuthoriseResponseRequisition` for supplying store, if it exists, set authorisationStatus = `pending` and send authorisation request to central (via message). Central would process this message and create authorisationQueue (with new logic, just checking programId on requisition matches master_list_id on authoriser). omSupply requisition with authorisationStatus = `pending` would not be editable. We also have to make sure that remote response requisition that is edited on central server, is sent to both the active site and the other party site (so that we can display approved quantity of link request requisitions lines)

Remaining logic would be the same as far as I can tell.

**Comment by andreievg** [comment]
proof concept for above comment: https://github.com/openmsupply/open-msupply/pull/1499

**Comment by andreievg** [comment]
Wanted to add some carry over tasks from proof of concept PR:

* Back end, response requisition not editable if authorisationStatus is 'authorise' or 'denied'
* Program_id logic in `create_response_requisition` should be removed when this issue is done (it's also mentioned in that issue https://github.com/openmsupply/open-msupply/issues/1504)
* Integration test to check authorisation (this may need to use authoriser API)
* Overall diagram of how this work

**Comment by DhanyaHerath** [comment]
closable @mark-prins?

**Comment by mark-prins** [comment]
🙏
