### ISSUE TITLE
Can see master lists in Catalogue > Master List but not when creating an Outbound Shipment

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1383]
## What went wrong? 😲

I can see the master lists in Catalogue > Master Lists: 

<img width="852" alt="Screen Shot 2023-03-20 at 11 36 26 AM" src="https://user-images.githubusercontent.com/74992958/226214046-1afd309c-79e5-417e-a68e-c52689d5274d.png">

I can't see them when I creating an Outbound Shipment: 

<img width="1433" alt="Screen Shot 2023-03-20 at 11 37 30 AM" src="https://user-images.githubusercontent.com/74992958/226214080-c1e5b379-c975-4550-ba31-a9a0fec1be37.png">

## Expected behaviour 🤔

I should be able to create an outbound shipment using the master lists assigned to this store. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

demo-open.msupply.org
User: cotedivoire
Pw: abidjan
Store: ESPC

**Comment by mark-prins** [comment]
The master lists available to you are those that the customer can see. 
This is so that any items distributed to them are visible in their store. There's a small problem, if the customer is 'external' i.e. not using omsupply then this behaviour is a bit strange. 

The [outbound shipment docs](https://docs.msupply.foundation/docs/distribution/outbound-shipments/#adding-lines-to-an-outbound-shipment-using-a-master-list) do say `Note that the lists show are those which are visible to the customer of the shipment.` so I'll close this issue.
