### ISSUE TITLE
Update pre-commit scripts and webhooks for new monorepo

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#14]

**Comment by mark-prins** [comment]
all done

- husky pre-commit hook is under ./client/.husky and is scoped to only compile changes since head 
- webooks updated and running on demo server. The build time has stretched out for f/e as I haven't separated out commits under a particular path: any merge to main will deploy
- the bundle size action is configured to only run for PRs which include files under `./client/**`
