### ISSUE TITLE
When adding an item to a (customer) requisition using master lists. All master lists are shown   

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1407]
## What went wrong? 😲
 
All master lists are shown even though the omSupply store and the receiving store have access only to 3. 

omSupply
https://drive.google.com/file/d/1FzUjoRCVJlC9N0xNDvQ3mhf0ijbHcxmM/view?usp=share_link

Store assigned master lists
https://drive.google.com/file/d/1xAD8MnqFgdj65BC8hpNcqSokBIXY1c6t/view?usp=share_link

## Expected behaviour 🤔
I would believe that only the master_list that are assigned to them shoud be available. isn't?

## How to Reproduce 🔨

Steps to reproduce the behaviour:
Create an internal order to be sent to the store using omSupply and sync 
1. Go to 'Distribution > Requisitions'
2. Choose the right requisition. Supply quantities. Create a outbound shipment
3. Click on add from master list 
4. See error. I can see all the master list

## Your environment 🌱
 - Version [e.g. 1.1.6]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by mark-prins** [comment]
Have checked and the destination store has access to all the listed master lists.
When adding items to an outbound shipment by master list, the list of the destination store is used, to ensure that they have visibility of the items. I'm now wondering if we need to also filter the items, so that only items which are 

- contained in the selected master list, AND
- are visible in the current store, AND
- are visible in the destination store

are shown. The first and last points are the same however, since item store visibility is controlled by master list.
We may have an issue with items which are visible in the destination, and not visible in the supplying store. Would that be right?

**Comment by alainsussol** [comment]
@mark-prins 


>  When adding items to an outbound shipment by master list, the list of the destination store is used, to ensure that they have visibility of the items. 

I think it is sensible...

> We may have an issue with items which are visible in the destination, and not visible in the supplying store. Would that be right?

I think that adding an item to supply to a customer means that you have stock for it which would imply that it is visible to you or was at some point anyway...

I think I would close the issue. It seems ok for me the way it is working now.

**Comment by mark-prins** [comment]
ok - thank you. sounds good.
