### ISSUE TITLE
Combine client and remote server installer

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1542]
## Is your feature request related to a problem? Please describe 👀

Create an installer which combines the server and desktop installers. Essentially the single user mSupply desktop install.

## Describe the solution you'd like 🎁
The installer will
- [ ] install the sqlite version of the server
- [ ] create a service
- [ ] start the service
- [ ] install the desktop version
- [ ] create a start menu shortcut for the desktop version
- [ ] Add the new installer to the jenkins build config

### Describe alternatives you've considered 💭
You can install the server and desktop separately. This is nicer though.

### Moneyworks Jobcode 🧰

DJUNCUST

**Comment by clemens-msupply** [comment]
Some feedback from when testing the current server installer. Questions that came up (Nick, Alain, Clemens):
- Will the installer install Postgres? if not should we say so in the installer?
- Say that the port input is only applicable for Postgres
- Does the server is registered as a service? what happens when we restart?
- Does the server needs to be run as Admin user?

**Comment by mark-prins** [comment]
> Will the installer install Postgres? if not should we say so in the installer?

The server installer asks if you want to install postgres, if you have selected the postgres option.

> Does the server is registered as a service? what happens when we restart?

Yes, the remote server is installed as a windows service. It is configured to auto start - is that what you mean?

> Does the server needs to be run as Admin user?

The service doesn't have to be, no. The default ( local system? ) is sufficient.
