### ISSUE TITLE
Cannot create any patients despite the correct permissions

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#1554]
## What went wrong? 😲
With cloud server setup with v7-04-01 and oms-remote site, can't really create any new patients from oms-site

## Expected behaviour 🤔
Let us create patients correctly as long as the correct permissions `Add patients` are set on cloud!

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Setup a cloud server setup with v7-04-01 and oms-remote site from `feature/programs` branch
2. In oms-site, opt to create a new patient
3. See error: it'll just throw authentication error: Permission denied error message.

## Additional Context
Details [here at the last part of this comment](https://github.com/sussol/msupply/pull/12766#issuecomment-1510836464)

**Comment by clemens-msupply** [comment]
At the moment only the mSupply permission "Edit Patient Details" is used. "Add patients" would make sense as well though.

Furthermore, you need extra document permissions to query/mutate the patient Documetns, but I think we can relax these permissions as well so that you only new existing mSupply permissions to access basic patient information.

**Comment by clemens-msupply** [comment]
I will close it for now since this should work on a correctly set up server (which is a bit tricky right now).
