### ISSUE TITLE
Checkbox on Master List View is always checked by default

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1597]
## What went wrong? 😲
The select all checkbox in the master list view is always set to true, and doesn't uncheck unless you click on another checkbox
<img width="1184" alt="Screenshot 2023-04-21 at 11 21 26 AM" src="https://user-images.githubusercontent.com/61820074/233506597-1d436dd1-3e27-491d-b625-7201671f0909.png">

## Expected behaviour 🤔
Shouldn't be checked on default

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱
 - Version [e.g. 1.2.3]
 - Platform [e.g. tablet, browser, windows desktop, macOS desktop, server]

**Comment by roxy-dao** [comment]
This happens in any place that uses select all @bijaySussol 🙏🏻

**Comment by bijaySussol** [comment]
> This happens in any place that uses select all @bijaySussol 🙏🏻

thanks @roxy-dao .

I am in need of quick pointer here.. What i see happening here upon testing this:

In here: 
https://github.com/openmsupply/open-msupply/blob/74c1f5d9cb2f1806bf7bb3793fc7835a36ca602e/client/packages/common/src/ui/layout/tables/columns/CheckboxSelectionColumn.tsx#L43-L44

The variable `allSelected ` become `True` and that is because `state.numberSelected` will be 0 and `Object.keys(state.rowState).length` will also be 0 as well, so The checkbox got selected.
The strange for me is, This `Object.keys(state.rowState).length` shows the correct number of Rows initially and when the window is loaded, the length of `Object.keys(state.rowState).length` become 0.

I can fix it adding a check to check if both are 0, then `allSelected` is False but that will again create the problem when checkbox is `selected` for the first time.

Are we dealing with some state where the state got over written?
if `Object.keys(state.rowState).length` stays non zero when the window is loaded, We have a solution.

Any help would appreciated. Thanks

**Comment by bijaySussol** [comment]
@mark-prins @roxy-dao : 
Another observation found today where the some `X` global state is controlling some other areas.
To verify that, Did test with Internal Order and the Stock take list window. From the Internal store or Stock take list page, Selecting some from any one and going back to another feature, The checkbox also get selected as well.

Looking at the storeAPI, Zustand.

**Comment by mark-prins** [comment]
I'm not seeing the problem with global state; I am getting something weird though when navigating around. 
I go to stocktake list and the `rowState` has all the rows. Navigate to another page, and back to stocktake list, and the `rowState` is empty. Selecting a checkbox and `rowState` has one record in it.
