### ISSUE TITLE
User Documentation for v1.1.11

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1658]
#### Program Requisitions
- [ ] #1657

#### Barcode scanning
- [x] Adding a barcode on the [stock view](https://docs.msupply.foundation/docs/inventory/stock-view/)
- [x] Create a sub-page to the [outbound shipment](https://docs.msupply.foundation/docs/distribution/outbound-shipments/) and explain about adding items using barcode scanner

#### Remote authorisation
- [x] Configuration - added a [remote authorisation](https://docs.msupply.foundation/docs/replenishment/remote-authorisation/) page
- [x] Usage also added to [remote authorisation](https://docs.msupply.foundation/docs/replenishment/remote-authorisation/#using-remote-authorisation)

### Other
- [x] Update the screenshot and detail on [the dashboard page](https://docs.msupply.foundation/docs/introduction/dashboard/)
- [x] Update screenshot and add export detail to the [Stock page](https://docs.msupply.foundation/docs/inventory/stock-view/)
- [x] Talk about the installers and installation types on the [introduction](https://docs.msupply.foundation/docs/introduction/introduction/)

### Moneyworks Jobcode 🧰

DJUNCUST

**Comment by mark-prins** [comment]
Add some updates and pages:
- the export function no longer orders items by the selected sort order, so that's been removed for the three languages for inbound, outbound & requisitions
- added 
- added [add item by barcode scanning](https://docs.msupply.foundation/docs/distribution/outbound_shipments/barcode-scanning/) page under outbound shipments
- update [outbound shipment](https://docs.msupply.foundation/docs/distribution/outbound-shipments/#adding-lines-to-an-outbound-shipment) to link to the barcode scanning page
- updated [introduction](https://docs.msupply.foundation/docs/introduction/introduction/#what-platforms-are-supported) with some detail on the various installer types
- updated [dashboard](https://docs.msupply.foundation/docs/introduction/dashboard/) to show the new layout and to talk about the new items
- updated the [view stock](https://docs.msupply.foundation/docs/inventory/stock-view/#exporting-stock) page to talk about exporting and editing stock lines, including scanning barcodes

**Comment by roxy-dao** [comment]
### Stock
> If a QR code which has batch and expiry information is scanned

If a... has a batch...

### Outbound Shipments
> You will be presented with a list Outbound Shipments (if you don't see any, you are probably just starting!).

You will... a list of Outbound...

>If you have more than shipments than the current limit, you can...

If you have more shipments than the...

> All the shipments for this customer appear in the list.

... will appear in the list.

- **Icon in first `TIP` if broken**

> The Information Panel allows you see or to edit information about the Outbound Shipment. It is divided in multiple sections:

It is divided into... 

- **Extra space after `How to open and close the Information Panel ? Seems to be missing sub-header? Also question mark for that is separated from text.`

> Comment: yYou can add a comment to provide further details about the new charge

Extra y

> Your customer has verified the quantity of the shipment. Goods are now part of their inventory .

Dot next to text.

> You don't have to update a shipment to next status in the sequence. 

... to the next...

> or by typing some or all of item name

or by... of the item name

> Once your item is highligthed, tap on the name or press Enter.

...highlighted...

> when allocating quantities at the batch number level

When allocating...

> you can edit a shipment line if the shipment has a status lower than Shipped.

You can...

> System will check if there is available stock for each selected lines and allocate them using the First to Expire, First Out (FEFO) logic.

... for each selected line...

> This a critical step because when goods are confirmed as shipped, they are no longer a part of your inventory records.

This is a...

### Barcode Scanning
> In addition, if the scanned barcode provides batch information and a match exists in your database, then all other batch lines are disabled, and the matching line is focussed.

... focused.

### Remote Authorisation
> In addition, you'll need to have the stores configured for normal usage in open mSupply, with the supplier and customer relationships configured. 

... Open mSupply... 

> The authorisation status can have a few different values:

Maybe bold the statuses so that they stand out from the explanation.

### Dashboard
> Open mSupply has a landing page which gives an overview of some statistics, and has some useful links, which we're talking about here, and also a system dashboard that uses Grafana, and gives an overview of all sites in your country (or organisation).

... which we'll talk about here...

- Add `Inbound shipments not delivered` to Inbound Shipments section
- Maybe add a colon after each label

> The item is visible in this store, but there is no stock recorded

Items which are visible in the store, but have no stock recorded.

> As well, there are buttons toward the bottom of the page which allow you to create shipments and requisitions.

There are buttons towards the bottom of the page as well...

### Introduction
> There are windows installers built for each release, providing:

Bold the device?

> (also available for macOS as a binary, not a dmg or package) A windows application which allows you to connect to a running server

Brackets after the sentence

> Quantify amounts required based on simple or complex formulae

... formulas (Which is what I believe the typo was 😉 )

> There are a lot of systems that manage inventory. mSupply has unique features that make it ideal for use for health supply chains in low resource settings:

... to use for health... (and also colon after each 

- Colon after each phrase

> You can implement mSupply in one facility, knowing that if you later decide to deploy thousands of sites, mSupply will still be the right tool.

Should this be Open mSupply since it's talking about Open mSupply in the first sentence? Though you do link mSupply afterwards... 🤔 

> The following table outlines some of the common terms used in mSupply, and also guides users of legacy mSupply regarding terminology improvements we have made.

...used in Open mSupply...

<img width="487" alt="Screenshot 2023-05-09 at 9 23 55 AM" src="https://user-images.githubusercontent.com/61820074/236938423-b6872ded-74b2-44e4-98d0-6b946aec1076.png">
Mix and match~
