### ISSUE TITLE
Stocktakes created using M/L not loading

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#1664]
## What went wrong? 😲
 

when creating a stocktake using a master list, the stocktake view won't load

![IMAGE 2023-05-03 13:49:50](https://user-images.githubusercontent.com/74992958/235819333-f24304b9-de36-48f7-99e2-0abae2ecc949.jpg)

## Expected behaviour 🤔

should load

## How to Reproduce 🔨

Steps to reproduce the behaviour:

https://demo-djibouti.msupply.org/ (user TMF Support)

Stocktake > New Stocktake > Using a M/L (Any)

**Comment by andreievg** [comment]
Looks like another pagination issue, due to loader. We were thinking about relocating pagination to graphql (by default no pagination, and it's not the service but the graphql layer that decides default pagination), I think it's worth looking at this now, or at the very least, to delete all pagination from loaders
