### ISSUE TITLE
Locations ordering consider numbers as characters

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1696]
## What went wrong? 😲
 
I am not sure it is really a bug but if somebody has numbered locations it might be strange to see this ordering: location 1, location 10, location 2, etc
![image](https://user-images.githubusercontent.com/11624516/236376486-e361147e-1e14-4afc-be74-65e107527399.png)

## Expected behaviour 🤔
I am not sure what the expected behaviour should be. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Add locations with numbers 
2. Check the order in the list
3. See that the ordering doesn't respect numbers order

## Your environment 🌱
 - Version [e.g. 1.1.11]
 - Platform [e.g. windows desktop]

**Comment by andreievg** [comment]
Thanks @alainsussol , but sorry can't really see how we can sort by both string and number. We would have to recognise part of a string as being a number (perhaps it's possible but very difficult since most of our sorting is done by database). In our triage meeting we agreed this can be closed. Btw can create strings with numbers that are still correctly sorted:

Empl01
Empl02
Empl10
Empl11
