### ISSUE TITLE
Creating multiple shipments from the requisition does not really create the shipment lines with exact supply quantities as entered in the requisition window.

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#1705]
## What went wrong? 😲
Creating multiple shipments from the requisition does not really create the shipment lines with exact supply quantities as entered in the requisition window.

## Expected behaviour 🤔
I'd expect the same behavior as it is currently in the mSupply Desktop

## How to Reproduce 
Steps to reproduce the behaviour:
1. Get a customer requistion to a oms store
2. In that requistion window, let's say the `Requested quantity` is 100. Supply 10 and click `create shipment` button
3. It does nicely. Outbound shipment with 10 is made
4. Don't finialise the requisition yet (90 is still remaining as well!)
5. Again back to the requistion, supply 20 and create shipment again
6. Now, See error: the new shipment doesn't take the new value(20), it'll take the same previous value? Also, that 'Remaining Quanity` column doesn't look updated after the second time.

## Your environment 🌱
 - Version: v1.1.13 apk
 
## Screenshots/Recordings
https://drive.google.com/file/d/1H95xUvIHE98A6W70RQ5UkGpUeMewqsNl/view?usp=share_link

## Additional Context
Found while testing https://github.com/openmsupply/msupply/issues/12729

**Comment by roxy-dao** [comment]
The invoices are generating correctly for me on develop and on the programs branch as well... 
https://github.com/openmsupply/open-msupply/assets/61820074/3ceca9af-7ebe-470f-9b3b-fd22c7e6d47c


From what I understand of your scenario:
- Store A has requested `100` units of item A.
- Store B supplies `10` and creates an inbound shipment - Invoice A.
-  Store B goes back and supplies `20` (which means that `10` units need to be supplied in the next invoice since `10` has already been supplied in Invoice A)
- Create an inbound shipment (Invoice B) - Unit Qty should be `10`
