### ISSUE TITLE
The packsize listbox is not updated with the right packsize of the stock allocated 

### ISSUE THREAD

**Issue by alainsussol** [openmsupply/open-msupply#1717]
## What went wrong? 😲
 
As title. 

![packsize list not updated](https://user-images.githubusercontent.com/11624516/236962032-ed49900a-880d-40b7-b5f7-6f601786d9e8.gif)

## Expected behaviour 🤔
I would expect that if one line is chosen then the packsize of that line would be selected. If many lines of different packsize are used then it should be any. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create an internal order with lines with quantity lower than all the packsize available for that item at the supplier store
2. In the customer requisition created, supply the stock and create an outbound shipment.
3. Click on a line to allocate stock. Put the quantity equal to a packsize you have instead of the requested quantity. Click on allocate  
4. See error. No packsize has been selected in the list.

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [X] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by roxy-dao** [comment]
Dup of #1715

**Comment by DhanyaHerath** [comment]
Triage: This is likely caused by expiry dates not existing for the lines - blank expiry dates should be counted as future, and allocated accordingly

**Comment by mark-prins** [comment]
The issue is not the expiry date, as suspected.
Problem is that the allocation will round down - if you have only pack size of 100 and request 50 units, then 0 packs are allocated, and the remainder is added to a placeholder row.

after discussion we agreed:
- to round up to the nearest number of whole packs
- display a message to the user to alert them that this has happened
