### ISSUE TITLE
Program: Approval status - pending -> none after sync

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1769]
## What went wrong? 😲
Created a program that needed authorisation... synced the site and found that the approval status changed from pending -> None. Also comment says: Approved by --- (even though it hasn't been approved)

https://github.com/openmsupply/open-msupply/assets/61820074/4daac18f-66ae-4063-82a4-e0767384dc43

## Expected behaviour 🤔
Status shouldn't change while syncing...

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a `Program Order`
2. Finalise
3. Go to receiving store and view Requisition, see that status is pending.
4. Sync.
5. Go back to Requisition and see that status is none which allows user to edit requisition

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by andreievg** [comment]
For full setup both of the preferences need to be turned on, and authorisers configured, as per the [short video](https://drive.google.com/drive/u/1/folders/1-5JlYyYA5jArUl6LbSAvH3qsWE--nO2I), I think that could be the issues (changing approvalStatus to None is expected behaviour, if authorisation is not fully configured. omSupply remote site doesn't have the data to figure it all out so requests authorisation by setting status to `Pending`).

The `Approved by demo` is from [Internal Authorisation](https://github.com/openmsupply/open-msupply/pull/1735), there was a comment to add an issue to generalise this behaviour: https://github.com/openmsupply/open-msupply/pull/1735#pullrequestreview-1423656776, i don't know if we created one yet

**Comment by roxy-dao** [comment]
Closed since works with correct config
