### ISSUE TITLE
[User Training Feedback] OUTBOUND SHIPMENT : Placeholder lines are in units when allocated lines are in packs

### ISSUE THREAD

**Issue by Pauline-mSupply** [openmsupply/open-msupply#1779]
## What went wrong? 😲

When creating an outbound shipment and asking for quantities higher than what I have in stock, the excess quantity is put in a placeholder line. The total of this line is in units and it is added to the total of allocated lines which is in packs. So the outbound shipment total quantity is wrong. 

<img width="1050" alt="Screenshot 2023-05-15 at 6 30 05 PM" src="https://github.com/openmsupply/open-msupply/assets/114633283/a133106b-72df-4973-ba6c-e82ec1abf11d">

## Expected behaviour 🤔

Placeholder line quantity should be aligned with the allocated line. If the line is in packs, the placeholder should also be in packs. If in units, it should be in units. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'demo-djibouti.msupply.org' and then on Outbound shipment / New outbound shipment 
2. Click on 'Add item' and then choose an item with units in stock
3. Capture a number of packs higher than the stock in 'Issue packs'
4. Click on 'allocate'
5. See error

## Your environment 🌱

 - Version: 1.1.12
 - Platform:
   - [ ] android (tablet)
   - [X] browser (chrome)
   - [X] desktop (potentially same issue)
   - [ ] desktop (macOS)
   - [ ] server (windows)
 
@richardmoizeau

**Comment by mark-prins** [comment]
> Placeholder line quantity should be aligned with the allocated line. If the line is in packs, the placeholder should also be in packs. If in units, it should be in units.

To clarify for implementation: the allocated line is always in packs. The problem is that it is possible to have multiple stock lines selected, and these can have different pack sizes. The placeholder row cannot know pack size in this scenario.

We can distinguish between a selected pack size in the pack size selector, and `Any`. Given this, and that we do not specify the pack size requested for placeholder rows - a possible implementation could be:

- If a specific pack size is chosen: display that pack size as the placeholder row pack size, AND
- treat the placeholder value as packs, AND
- multiply the placeholder quantity by the pack size when saving the shipment, so that the stored placeholder quantity is in units, AND
- when editing this item, do the placeholder calculations again

- If the pack size is `Any` then behave as normal, AND
- drop the total on the packs column ( or possibly don't count the placholder quantity? )

**Comment by mark-prins** [comment]
Revised decision. We'll remove the total from the pack size column.
There's a desire to also change the column order - but we don't want to confuse existing clients.
Existing mSupply users are comfortable with placeholder rows in units and we don't want to confuse them either
