### ISSUE TITLE
[User Training Feedback] : in 'View stock' window, enable "group per item" button 

### ISSUE THREAD

**Issue by Pauline-mSupply** [openmsupply/open-msupply#1792]
## Is your feature request related to a problem? Please describe 👀

When a user is looking at the current stock, it is usually not sorted per item alphabetically so the user does not see all the items in their stock. They also tend to calculate the total quantity for an item on the side (on a paper) to know exactly how much they have.

## Describe the solution you'd like 🎁

There is a button called "group per item" in other menus that could be very useful here.

### Describe alternatives you've considered 💭
None

### Moneyworks Jobcode 🧰

No moneyworks jobcode. I am aware that there is no more budget for customisations for Djibouti but I feel like it should have been noted somewhere.

**Comment by mark-prins** [comment]
We've discussed changes to the stock view and item view previously (at length!) and there are many different opinions on this one!

There is already an item list view, and users can use that page rather than the stock view, if they wish to group by item. If we add grouping to the stock view, we are adding complexity and making the stock list provide much the same functionality as the item list: in our discussions we were wondering if we could do that - just combine the two lists, since they are similar. The final decision was that combining them would cause more confusion, making each list harder to use and making the data less clear. We have decided to retain the two distinct lists.

Note that in the item view, you can already see a total of the stock on hand, among other details:

![image](https://github.com/openmsupply/open-msupply/assets/9192912/6a986567-a2bb-44b6-9832-50e12f7471d0)

As for the sorting - yes, the default sort of the stock view is by expiry date (descending). You can however click the item name column, and sort by item.
