### ISSUE TITLE
Apk crashes when we quit oms clicking Back button in mobile tablet

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#1871]
## What went wrong? 😲
In mobile tablet, I've noticed this a lot: click back button in mobile tablet, until the app closes. Reopen and see that the app crashes and is unable to open on first load. Again opening it works though! 

## Expected behaviour 🤔
No sudden crashes

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Make sure oms is open with an active user login session
2. Click back button in mobile, until the app closes.
3. Now, open it again
4. See error: it won't open again!

## Your environment 🌱
 - Version: v1.1.13 apk
 - Platform:
   - [x] android (tablet)
 
## Screenshots/Recordings
https://github.com/openmsupply/open-msupply/assets/59193490/1023b02a-167a-454d-b932-5f5dc62bc69c

**Comment by mark-prins** [comment]
I've tested using an emulator and a samsung tablet. For me, clicking the back button once minimises the app, clicking the app icon then reopens the app without a problem.

I'll add in handling of the back button to navigate back, as I think that's a nice idea - but have been unable to reproduce the issue as stated here.

**Comment by clemens-msupply** [comment]
Can confirm that I can reproduce the behaviour + crash on the Lenovo tablet

**Comment by kahn-msupply** [comment]
🧪 Testing

I was testing this issue to see if I could confirm if resolved, I found that if I hit the back button on Android tablet omSupply v1.3.00 enough times, I was greeted with the omSupply logo indefinitely (screenshot), or loading icon (recording). I was able to replicate multiple times, but now cannot reproduce... I was spamming the back button in order to see what happened. Seems to happen occasionally.

Screenshot:

![Screenshot_20230904_163500_openmsupply-client](https://github.com/openmsupply/open-msupply/assets/132425100/294cc386-8eb1-4cc0-bfd5-cf8e117f875e)

Recording:

https://github.com/openmsupply/open-msupply/assets/132425100/0d3e71b8-c6d3-41e9-80ed-1dee86099142

**Comment by mark-prins** [comment]
Thanks @kahn-msupply - can you add tablet and android details please? The issue was resolved for all the tablets which I have, and behaviour differs on different tablets. We'll need to retest on whatever you are using

**Comment by kahn-msupply** [comment]
> Thanks @kahn-msupply - can you add tablet and android details please? The issue was resolved for all the tablets which I have, and behaviour differs on different tablets. We'll need to retest on whatever you are using

@mark-prins I have updated my comment with Tablet details :) Let me know if I can do further testing

**Comment by AnushaUp** [comment]
This isn't happening anymore. Moving this to done.👍
