### ISSUE TITLE
Repack - Log

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1872]
## Is your feature request related to a problem? Please describe 👀

When repacking there's no easy way to see where a particular stock line came from. It might be helpful to have a log entry for the new (repacked) stock line which says something like 'repacked from stock line x' 

## Describe the solution you'd like 🎁
An entry showing in the log

**Comment by nisha-dangol** [comment]
# Testing
Tested in apk v1.2.0-RC2

## Tests
- [x] Go to a repacked stock line and click log.

Currently, I see some random ID like characters instead of clear message which says something like `'repacked from stock line x'` in the `Details`. Is this expected here? @mark-prins @roxy-dao 
![photo_2023-07-13 4 09 53 PM](https://github.com/openmsupply/open-msupply/assets/59193490/bccfe343-f2ec-4850-afc1-22e6c06c7b4f)

**Comment by roxy-dao** [comment]
> Currently, I see some random ID like characters instead of clear message which says something like `'repacked from stock line x'` in the `Details`. Is this expected here? 

Yes, currently just shows the stock line ID, can change that to be clearer and say `repacked from stock line {id}`

**Comment by mark-prins** [comment]
Adding in `Repacked from stock line {id}` would be good.
Can we do this in front end in order to get translations?
