### ISSUE TITLE
Have to allocate twice in outbound shipment created from requisition

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1894]
## What went wrong? 😲
https://github.com/openmsupply/open-msupply/assets/61820074/36a8466d-70fe-4a8a-9f47-142d19506572

## Expected behaviour 🤔
User should only have to allocate once. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Store A send a requisition to the store
2. Store B receives requisition, issues some stock and creates outbound shipment
3. Allocate stock through modal. 
5. When you allocate again from action bar, you will be supplying twice as much as what you wanted to supply

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by andreievg** [comment]
Maybe look into UI test for this, or at least flagging that it would be beneficial here

**Comment by kahn-msupply** [comment]
🧪 Testing - PASSED

- [x] As per the issue - create an outbound with a placeholder row. Allocate in the modal - if all of the placeholder quantity is allocated, the placeholder row should be removed.

LGTM

One thing I did notice, is that the item line will not appear if stock is not allocated in the modal. When you click OK, there is no item added to the Outbound shipment. If Pack Qty is changed to zero, the item will be removed from Outbound Shipment. Probably by design!
