### ISSUE TITLE
Compatibility Matrix

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1914]
Add compatibility matrix to public docs (which version of omSupply works with which mSupply version):

https://github.com/openmsupply/open-msupply/blob/8004e0cd9d9b2ec6b355d8e7484bfcc32611da2f/server/service/src/sync/settings.rs#L4

https://github.com/openmsupply/msupply/blob/b690ffa2b7d5f1a017d8bb02088545f4093bd049/Project/Sources/Methods/syncV5API.4dm#L17-L18

**Comment by mark-prins** [comment]
Totally confused by mSupply versioning and how to relate the releases with the values in `version_number_return`
This is my best guess, based on versions released rather than version numbers in the code:

| omSupply       | mSupply                     |
| :------------- | --------------------: |
| 1.1.00 - 1.1.15  | 7.04.03 - 7.05.04       |
| 1.2.00+            | 7.05.05+                     |

Would that be the sort of thing you had in mind @andreievg?

**Comment by andreievg** [comment]
Hmm, I tried with git blame, as [per screenshots](https://github.com/openmsupply/open-msupply-internal/compare/main...main(OM1914))

There are some instructions on how the versioning work in the readme files, and I think together with git blame we can deduce historic compatibility and install some process to do this when compatibility is updated.

Basically:

| omSupply       | mSupply                     |
| :------------- | --------------------: |
| 1.1.11 - 1.1.16  | 7.04.01+     |
| 1.2.00+            | 7.05.05+                     |


i.e. the min version in mSupply didn't change so it still supports earlier versions

**Comment by mark-prins** [comment]
thanks @andreievg - have updated the docs 🙏
