### ISSUE TITLE
UI: Prescription window

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#1956]
#### Header, Content Area, Side Panel and Footer
- Use the `Outbound Shipment` as a base
    - Remove Service Charge from Side Panel (?)
    - Remove Transport Details from Side Panel 
- Statuses for `Prescriptions` are: New, Picked and Verified. 
- The header should contain: 
    - Patient name (can search by code or name)
    - Replace customer ref with `Clinician Name`: can search by code or name (?)
- Items should be grouped automatically.

### Additional context 💌
![dispensary-detail-view](https://github.com/openmsupply/open-msupply/assets/61820074/5db82937-aaa2-414e-bb3e-8c4c070de486)

### Moneyworks Jobcode 🧰
OMS:MVP | Open mSupply MVP Prescription Module
-- | --

**Comment by DhanyaHerath** [comment]
Agreed that navigating away with no lines should delete the prescription - I wouldn't mind an alert or something to tell users that's what's happening but can come later

**Comment by andreievg** [comment]
> Status of Invoice should change to picked once a line has been created

Shouldn't this be done with manual status change at the bottom ? (I think that's ok for MVP, rather then extra logic on line creation)

**Comment by andreievg** [comment]
@DhanyaHerath 
> Agreed that navigating away with no lines should delete the prescription - I wouldn't mind an alert or something to tell users that's what's happening but can come later

If prescription was created, with lines and then some action was taken. Coming back to a prescription and removing the lines should also remove that prescription when navigated away ?

@roxy-dao what is navigated away mean here (can we capture this) ? 

Is this really needed for MVP ?

**Comment by andreievg** [comment]
> Batch should be auto-allocated (First to expire)

Do we really need to change the logic of line allocation for MVP ?

**Comment by andreievg** [comment]
Anther general note, we would have to think of how to break this task down into smaller reviewable chunks (be it a bunch of stacked PR that don't really work independently or independent bits of limited functionality)

**Comment by roxy-dao** [comment]
> Shouldn't this be done with manual status change at the bottom ? (I think that's ok for MVP, rather then extra logic on line creation)
OG changes the status of the prescription invoice to `fn` when an invoice line is created to reduced the amount of `nw` prescriptions...

> @roxy-dao what is navigated away mean here (can we capture this) ?
Yes, can capture changing page.

> Anther general note, we would have to think of how to break this task down into smaller reviewable chunks (be it a bunch of stacked PR that don't really work independently or independent bits of limited functionality)
Was going to... but wasn't too sure how to break out FE issues 🙇🏻

**Comment by andreievg** [comment]
I still think we should keep those two out of mvp (navigate delete and change status on line addition).

> Was going to... but wasn't too sure how to break out FE issues 🙇🏻

Might be easier to think about the break down when this issue is being implemented, I would assume for the limited and independent functionality it would be something like this:

* Able to search and create new patient invoice (search patient and calling insert mutation), leading to a blank detailview for prescription
* Able to navigate to existing prescription by double clicking outbound
* Layout for the prescription (table buttons, but they don't do anything)
* Able to update prescription with clinician (clinician search and insert mutation)
* etc ..

Btw don't really need to create new issues for this, can do a pr like "#1956.1 Can search for patient and create prescription" (and only the last PR actually fixes: #1956.1)  

You may need to edit code in other areas, like outbound shipment (to extract logic into common component), this is a bit hard to predict, but if that's done in a separate PR that would also be great, but yeah if it's too hard it's ok to do it in existing PR, as long as it's well explained)

**Comment by DhanyaHerath** [comment]
@roxy-dao Thanks for writing all this up! 

I would split out the changes to the invoice line into a separate issue, just to make that part separate and easier for reviewers. For the rest, I agree with Andrei that it is ok to go in PR chunks. 

I would also split out the part about auto-allocating stock into a separate issue (sorry if I confused you with talking about it!) I think we __should__ do that, but it can be separate to this work, and not part of the MVP, particularly as in mSupply it uses that behaviour throughout the app, not just for prescriptions.

**Comment by andreievg** [comment]
@DhanyaHerath, what about the other two, do you think it should be part of MVP ? (I vote for "no", still capture the requirement for future, to be considered when optimising UI/UX)

* Status of Invoice should change to picked once a line has been created
* Navigating away or closing empty prescriptions (with no lines) should delete the prescription?

**Comment by DhanyaHerath** [comment]
@andreievg agreed with no for both

**Comment by roxy-dao** [comment]
Have added the above three points to future works and removed from issue~
