### ISSUE TITLE
Manually sync user info

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1987]
## Is your feature request related to a problem? Please describe 👀

During TL deployment, permissions needed updating for user, and due to intermittent internet it was hard to discern if permissions were updated (which happens on login, but only if there is connection to central server).  Also show when user was last successfully logged in.

## Describe the solution you'd like 🎁

kudos: @craigdrown 

Another manual sync for User Info/Permissions, would also show last user permissions update.

### Describe alternatives you've considered 💭

Syncing user permissions (would take awhile to design and coordinate) 

### Additional context 💌

Proposed solution would require storing user password in app data (not a big fan of this), or some token that mSupply can give out that we can store on remote server and use to get User Info/Permissions (TokenBucket)

### Moneyworks Jobcode 🧰

PG23OMD

**Comment by nisha-dangol** [comment]
- [x] Login
- [x] Wait a couple minutes
- [x] Go to central and remove some permissions or add some permissions
- [x] Go to sync page
- [x] Click Sync Now button under Sync User
- [ ] Can also disconnect central and try update (Last successful sync should not update in this case)


Hi @roxy-dao @andreievg 
I have some questions/confusions regarding this. 
1. I notice that changing the user password while the user is logged in will give `unknown sync error-> Error: LoginFailure` message, but at the same time will let the user(still logged in) create sync records like adding/editing names. Shouldn't that `LoginFailure` error should log-out the user as well? See [this video reference](https://recordit.co/KBjjQsX5aG).
<img width="706" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/59d28a54-9b64-4fe6-9f53-e4ac26e843fb">

2. When I edit some user permissions (in mSupply cloud) like `Create stocktakes` permission, shouldn't that also reflect accordingly when I sync with the new Sync button here? In my case, I do not see the permission updating at all. Also, since updating user permissions (or changing user passwords) on mSupply Cloud is not creating any sync records, I can't really tell if we can expect the permissions to be reflected as well.

3. In [your screenshot/video](https://github.com/openmsupply/open-msupply/pull/2080#issue-1843948552), I see the new Sync title as '**Sync User**' while in my setup, I see '**User Synchronisation Status**' . Which one is the correct one here?
<img width="781" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/8350f210-53e6-4780-9a10-bb5559724843">

<img width="750" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/1c67fbea-183f-4d93-ad7d-c2dbd538356d">


Note: I noticed these in my local 'develop' branch, but I'd be happy to test them in the build exe's as well!

**Comment by roxy-dao** [comment]
> 1. I notice that changing the user password while the user is logged in will give `unknown sync error-> Error: LoginFailure` message, but at the same time will let the user(still logged in) create sync records like adding/editing names. Shouldn't that `LoginFailure` error should log-out the user as well? See [this video reference
> 
> 2. When I edit some user permissions (in mSupply cloud) like `Create stocktakes` permission, shouldn't that also reflect accordingly when I sync with the new Sync button here? In my case, I do not see the permission updating at all. Also, since updating user permissions (or changing user passwords) on mSupply Cloud is not creating any sync records, I can't really tell if we can expect the permissions to be reflected as well.
> 3.  I see the new Sync title as '**Sync User**' while in my setup, I see '**User Synchronisation Status**' . Which one is the correct one here?

1. [Will create an issue for this. ](https://github.com/openmsupply/open-msupply/issues/2092)
2. Yes it should reflect the permissions changed in central if server can connect to central (and password has not been changed). I can see on your screenshot that the last permission update was 7 minutes ago. If the permissions couldn't be updated, there would be an error as shown in your screenshot. 
3. `User Synchronisation Status` is correct. The screenshot you provided was just the initial set up... it changed throughout the PR

**Comment by nisha-dangol** [comment]
> 1. [Will create an issue for this. ](https://github.com/openmsupply/open-msupply/issues/2092)
>
Thanks!
<br><br>

> 2. Yes it should reflect the permissions changed in central if server can connect to central (and password has not been changed). I can see on your screenshot that the last permission update was 7 minutes ago. If the permissions couldn't be updated, there would be an error as shown in your screenshot.
>
Regarding this, yes I tried the re-login with updated password (and removed one permission on Cloud as well). On re-login, I was still able to create stocktakes, meaning the user permission is not being respected! Will submit an issue!
<br><br>
> 3. `User Synchronisation Status` is correct. The screenshot you provided was just the initial set up... it changed throughout the PR
>
Cool!
