### ISSUE TITLE
Mutate patient without program config

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#2023]
It should be possible to edit a patient if there is no program config at all, e.g. no patient data schema and no patient document_registry entry.

This would require:
- some graphql endpoint changes to be able to upsert a patient without creating a document
- update the frontend to contain a default patient schema and a default patient UI schema (or have a separate hardcoded editing modal)

This feels a bit cumbersome to me and I wonder if we should just always create a patient document when editing a patient in omSupply. The only thing this is needed is a default entry for the patient schema and the patient document_registry on the central server.

After discussion with @andreievg:

Currently, it's not a big issue to save documents for every patient. However, in the future we want to be able to disable documents for patients if required. For this reason it would be desirable to change the API now so that a patient can be updated without creating a document.

**Comment by clemens-msupply** [comment]
Without the program config the patient data can only be stored in the `name` table.
However, even the basic patient schema already can record more data than can be stored in the name columns, i.e. the current patient endpoint assumes that there are patient documents.

Note, even with https://github.com/openmsupply/open-msupply/issues/1854 there is more patient details in the typed fields than can be stored in the `name` table.

For this reason I think we should have a separate set of endpoints that can be used to update a patient without updating a document.
If the frontend detects that the program config is missing the FE has to use these endpoints.
Endpoints can be named like `insertBasicPatient` / `updateBasicPatient`

**Comment by andreievg** [comment]
We had a chat.

**Summary**

Extending patient schema would require using documents.

Use `insertBasicPatient` and `updateBasicPatient`. We wouldn't need any central configurations for basic patient if the form schema for basic patient is hard coded in front end (could also have a seperate non json-form UI for basic patient, but it would be less work for now to do it using json-form).

With above, we would't be able to do non extension customisation to the form (i.e. shuffling UI fields around), these would either require a document or a plugin (plugins could also extend the patient creation). With form schema for basic patient living in the central configuration, we would need to do mSupply migrations to add it, and it creates more use cases to think about (central configured form-schema with document and without document)

Maybe `insertPatient` and `insertProgramPatient` or `insertPatientDocument` endpoints (just because `basic` would be `standard`, more comment then program, and would be able to extend form without program, but with document)

**Clarification**

Something that would be useful to document for testers and reviewers:

How does name map to document on front end and would this be different for base json-form that is hard coded in UI and base document patient ?

How permissions work for document and patient document ?

**Comment by clemens-msupply** [comment]
> Maybe insertPatient and insertProgramPatient or insertPatientDocument endpoints (just because basic would be standard, more comment then program, and would be able to extend form without program, but with document)

Just had the same thought. I like `insertPatient` and `insertProgramPatient`
