### ISSUE TITLE
Context error with v1.2.01

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#2072]
## What went wrong? 😲
 
After installing v1.2.01 the demo server failed to start. The log records that db migrations start and then fails with this error:

```
2023-08-04 15:09:32.077312200 [ERROR] <omsupply_service::omsupply_service:71>:panic occurred PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: DBError { msg: "UNKNOWN", extra: "\"\\\"relation \\\\\\\"context\\\\\\\" does not exist\\\"\"" }), location: Location { file: "C:\\Program Files (x86)\\Jenkins\\jobs\\omSupplyMain\\workspace\\server\\server\\src/lib.rs", line: 258, col: 10 }, can_unwind: true }
```
The database shows as v1.2.1

The reason for the error needs to be investigated, in case this will affect existing users who try to upgrade to v1.2.01
Attached is a backup of the failed database (this is on the demo server as `omsupply_v3`)

[dump-omsupply-202308070955.zip](https://github.com/openmsupply/open-msupply/files/12270493/dump-omsupply-202308070955.zip)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by andreievg** [comment]
Hmm, I thought it could be because this [file didn't run](https://github.com/openmsupply/open-msupply/blob/f9f03135b1ac2548e733ad0904a10f7589d5c074/server/repository/migrations/postgres/2023-06-20T10-00_program_permissions_update/up.sql) during migrations. But after removing it, i get a different error ('column context does not exist').

I ran a full migration test on the tag, seems to be passing. I only wanted to spend a little bit of time on this atm, so haven't tried restoring backup and upgrading yet (that would be the best way to replicate i guess)

**Comment by mark-prins** [comment]
A victim of development, it would appear.
There's an RC build (1.2.0-RC3) on 11 July, then the context table is introduced in 2e7f95c89486886d89807fd68675e88bcd7183d6 and later the context table is [pmoved to 1.2.0](https://github.com/openmsupply/open-msupply/commit/a1b8089f03c205240987f81e4c6be790f76f53d4)

The affected database is claiming to be 1.2.1, and yet is missing the context table which is in 1.2.0.
Adding the table, running the below to migrate data, and continuing with the `context_table` migrations has resolved the issue.


```
insert into context (id,name)
select distinct context_id, context_id from document_registry
where context_id not in (select id from context);
```
