### ISSUE TITLE
Auto allocate stock straight away for faster input for pharmacists

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#2091]
## Is your feature request related to a problem? Please describe 👀
In mSupply, when you choose an item to issue (either in a customer invoice or a prescription), the software automatically 'selects' the line you can issue from based on FEFO: 

![image](https://github.com/openmsupply/open-msupply/assets/29744386/bcbcd806-62a0-4c95-a9e5-b7cd8f64bb66)

If a line has expired, then it chooses the next best one: 

![image](https://github.com/openmsupply/open-msupply/assets/29744386/4796ae80-53a5-4ae2-ad9a-720e61606fc8)

This means that you can enter in a value into the 'Quantity' field, and you are able to just click `OK` and have that line selected. 
This is quite handy particularly in contexts like prescriptions where you want to move quickly. 

## Describe the solution you'd like 🎁
Would it be possible to implement something like this in omSupply?

### Additional context 💌

Part of excluded work from https://github.com/openmsupply/open-msupply/issues/2071 

### Moneyworks Jobcode 🧰

OMS:MVP
--

<br class="Apple-interchange-newline">

**Comment by DhanyaHerath** [comment]
@mark-prins @roxy-dao You two have worked the most on that issue window modal, so let me know if you think this would be a reasonable change to make!

**Comment by mark-prins** [comment]
I like the idea, but am now gun-shy about tinkering with this modal.
We did have auto allocation originally, and refactored it away because it spooked people - the automatic allocation was unexpected and the allocation process, and therefore the results, too hard to understand.

This was addressed by tidying up the placeholder row and replacing auto allocation with the `Allocate` button. I now find this annoying and would rather not have the additional step. Am reluctant to remove without some use feedback though, I wouldn't want to regress the usability of the window!

**Comment by roxy-dao** [comment]
It's a bit easy to forget to press the `Allocate` button and press `Ok` too... in which case the user will need to add the item again... (but they probably will just be confused as to why the item doesn't appear on the detail view since there's no message saying they have to allocate or anything)

**Comment by DhanyaHerath** [comment]
@roxy-dao Totally - I actually do that every time 😅

**Comment by roxy-dao** [comment]
Can we close this issue now since it's been implemented in #2293?
