### ISSUE TITLE
Programs: ensure user will update the encounter status

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2143]
## Is your feature request related to a problem? Please describe 👀

When creating a new encounter, it is easy to miss the step when user is supposed to update the encounter's status cause it is located in the headers. 

The risk is that we will have a lot of encounter with default status "Pending" or "Missed" even though they are in fact "Visited" but user simply forgot to update the status. 

## Describe the solution you'd like 🎁

if encounter's status = `Pending` and new data has been added, when clicking on the `Save` button a popup window would ask user whether to update the encounter's status to "visited" or not 

### Describe alternatives you've considered 💭

We could also add another button in the bottom right corner entitled `Confirm XXX` (similar to what has been done for shipments' status update with the possibility to update the encounter's status to either `Visited` or `Cancelled`

![Screenshot 2023-08-28 at 3 12 25 PM](https://github.com/openmsupply/open-msupply/assets/74992958/bf747607-f87b-4c88-bd8f-ef013a6b6bd9)

We would need to keep `Save`  as a separate button since you could theoretically update an encounter without changing the status and user can still update an encounter even when status = "Visited".  

### Additional context 💌

![Screenshot 2023-08-28 at 3 09 35 PM](https://github.com/openmsupply/open-msupply/assets/74992958/129ac79a-6b51-40ff-9600-fe5edd642852)

### Moneyworks Jobcode 🧰

PG23THRFD

**Comment by clemens-msupply** [comment]
Sounds good, small suggestion: Only autoselect the button as "Save as Done" when the encounter is in the past. Otherwise, you might just update a schedule encounter, e.g. change date, and the encounter is still pending.

**Comment by clemens-msupply** [comment]
I implemented it. After playing around with it ran into this case:
- Encounter is in the past and patient didn't visit
- You go back to the encounter to add more information, e.g. a comment why the patient didn't show up
- After the edit the button suggests to "Save as Visited" which would be wrong

So either we need another status after all. Or we have two save buttons, one to just save the encounter as it is and one to change the status + save the encounter. For example:



![Image](https://github.com/openmsupply/open-msupply/assets/88299195/d0ae9e22-f3a7-4bb5-a205-575bf4452638)

**Comment by clemens-msupply** [comment]
After discussion with @richardmoizeau 
- [ ] toolbar to status picker
- [ ] Only one save button
- [ ] Confirmation modal when changing status

**Comment by clemens-msupply** [comment]
Above doesn't really work either... @richardmoizeau , @mark-prins , @anisha-msupply : maybe you have some other ideas. Problem is that with the missing status picker in the toolbar you can't just change the status without making other changes because the save button would be disabled... (Furthermore, having a confirmation modal isn't that nice in the first place.)

Summary of the requirements:
- Main requirement: when saving a Pending encounter make it difficult for the user to forget changing the status to Visited
- Still be able to leave the status as Pending in case the patient didn't visit (and not tempt the user to just change the status to Visited, see above)
- Be able to just change the status
- Visualize when an encounter has been modified and need to be saved

Possible solution: have a button that always requires two steps:
1) Press save button will open a menu with sub-actions for setting the status: "Current status" | "Pending" | "Visited" | "Canceled"
2) Selecting sub-action will execute the action without confirmation
A modified encounter could be visualized through a button icon, i.e. button is always enabled to be able to change the status.

**Comment by mark-prins** [comment]
@clemens-msupply I like the possible solution you have, though I'd modify slightly:

- save button is always enabled ( otherwise how do I update only the status? )
- pressing save opens a confirmation dialog ( more consistent with the rest of the site, the smaller menu is more difficult to use, you can put more information on a dialog )
- the dialog asks you to 'Select the status' ( it would be good to have the status values as buttons, to reduce a click. I wonder if `Pending` & `Visited` buttons would look odd? ) Do we need a `Cancelled` status button?
- and has a `Cancel` button to close the modal without saving. though, if cancelled is a valid status, is that confusing?
- show a modal if validation has failed and the system won't save the record (i.e. the current 'disabled button' state)

I'm also wondering about adding the status field back. With the above solution, you have to know that you click 'save' to change the status - that information is hidden from you.

All that said, I do like the multi-status button and how that is consistent with other areas of the site. My concern with it is how to default to a value (like you say, should it be 'save with current status'?), and whether having status under it hides the ability to change the status.
