### ISSUE TITLE
internal orders charts are wrong

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2194]
## What went wrong? 😲

when creating a internal order:
- charts says that my target quantity is 3 x 1623 units = 4869 units
- stock on hand = 1780 units so system suggests to order 3090 units
- but stock on hand chart visually indicate that I currently have enough stock

![Screenshot 2023-09-06 at 4 26 51 PM](https://github.com/openmsupply/open-msupply/assets/74992958/e0d8c4f5-c207-4606-9c81-76219568f08b)

## Expected behaviour 🤔

charts should show that I'm missing 3090 units (orange chart)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to https://demo-open.msupply.org/replenishment/internal-order/12?sort=itemName
3. Click on Replenishment > Internal Order 
4. Create new order
5. Add "Amoxicilin"
6. make sure you don't have already enough stock
7. See error

## Your environment 🌱

 - Version: 1.3.00
 - Platform:
   - [ ] browser (Chrome)

**Comment by richardmoizeau** [comment]
If you look at the video, it looks like the correct chart is displayed before being replaced by the final one: 

https://github.com/openmsupply/open-msupply/assets/74992958/69ac7959-ad63-4d1c-8518-1be26a70f136

screenshot from the video:

![2023-09-06 17 00 39](https://github.com/openmsupply/open-msupply/assets/74992958/6ef63c33-75a4-4b97-84f0-4b2e9cdad8d2)

**Comment by roxy-dao** [comment]
Screenshot 1 says that suggested quantity is 0, so it won't show the suggested quantity since your min MOS is 1 and you have enough stock for 1 month... suggested quantity is calculated only when your min MOS < SOH... (probably needs more discussion on how this is calculated)

The SOH bar being full width makes sense to me if there's nothing else to display 🤔  Though... I get it might look confusing since it can suggest that your SOH is equal to how much you use within x amount of months..

**Comment by mark-prins** [comment]
The problem with the chart is that there is 3220 units consumed already in September!
This is causing the jump in AMC - but the problem is that the final month in the chart is replaced with estimated data because we are still in that month. The estimate is incorrect in this case - we have already used 3220 and the estimated consumption is 1623!

In summary, we need to improve the calculation of the current month

**Comment by roxy-dao** [comment]
😆
