### ISSUE TITLE
AMC calculation is wrong (at least on the internal order chart 🙃)

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#2195]
## What went wrong? 😲
 

created an internal order for item `030453  / Amoxicillin 250mg tabs` in [demo server](https://demo-open.msupply.org/) (store Waikato District Store)

if AMC is based on the last three months, then something's wrong in the calculation: 

![Screenshot 2023-09-06 at 4 46 24 PM](https://github.com/openmsupply/open-msupply/assets/74992958/bd6295da-854b-468e-b013-84ed2b54e3dc)

Details: 
- August consumption = 1000
- July = 650
- June = 0

AMC should be 550 units for systems calculates 1623 units!

Not limited to the internal order; same AMC value appears in Catalogue > Items

## Expected behaviour 🤔

AMC should be 550 units for systems calculates 1623 units!

## How to Reproduce 🔨

Steps to reproduce the behaviour:

Create an internal order for any item, check the last three month in the consumption history (monthly) chart and calculate your own AMC (last three months / 3)

tested with item `030453  / Amoxicillin 250mg tabs` in [demo server](https://demo-open.msupply.org/) (store Waikato District Store)

## Your environment 🌱

 - Version: 1.3.0 
 - Platform:
   - [ ] browser (chrome)

**Comment by roxy-dao** [comment]
The calculation seems to be correct on my end 🤔

**Comment by andreievg** [comment]
@richardmoizeau ohh, this is because you have consumption in september:

![Screenshot 2023-09-07 at 5 47 32 PM](https://github.com/openmsupply/open-msupply/assets/26194949/966ca6b1-1da6-410f-8469-fb83ae0a14c1)

This is generally an interesting question, I remember discussing it once, and didn't quite come to a conclusion. 

But for now should the chart show september consumption and october projected ?

**Comment by mark-prins** [comment]
i was looking at the same problem in #2194 
I think that we should show september as projected and exclude sept from the consumption. In that example - there is amc of 543 for August, and then we have 3220 used in September - this blows the AMC out to 1623 and that's the estimate we show for September.

Though we also know that estimate is incorrect, since we've already used 3220. And then on the chart, we don't show that 3220 consumption but the number is affecting AMC which means the user doesn't know why the AMC is so huge.

**Comment by roxy-dao** [comment]
Fixed in PR above
