### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#22]
A packaged installer for the web app and remote server. This is for remote off-line sites (cloud instances can be set up manually).

Since we have some experience with Setup Factory, this seems like the way to go. Using sqlite for V1 would mean pg ‘state’  doesn’t need to be maintained for now, which would make installer setup a bit simpler. 

Should we explore a more modern looking installer / bundler?

**Comment by andreievg** [comment]
> Should we explore a more modern looking installer / bundler?

As an outcome of meeting discussion
* It would also be good to dynamically configure installer during build, in SetupFactory we have to replace certain hard coded string tokens with dynamic configurations (like the version of current build)
* It's only really Mark, Ujwal and Andrei that had any experience with SetupFactory, there was a comment from Craig that using SetupFactory would be good because we already have experience with it, I wonder if that's still true given the above. I think if we do explore different installer / bundler it would be good to consider simplicity of use vs functionality (ideally simple and with lots of feature).

Things to consider for installer ?

* Install vs Upgrade ?
* Ability to load demo data (either in installer or in initial screen config phase)
* Database (although we mentioned it's out of scope for V1, we should consider our strategy for installing and running postgres)
   * It should run on unique port (not standard 5432) to avoid conflicts with existing infrastructure
   * Do we run as a service or do we maintain PG state with remote server (i.e. we can bundle pg binaries and use cli to create pg cluster and start pg if it's not running during remote server startup ?)
* Different flavours of remote server (postgres/sqlite on android/mac/window for M1/x86), do we have different installer for each (where installer is appropriate)
* Signing
* Automating install process
* Publishing installers/upgraders

**Comment by ujwalSussol** [comment]
> * It would also be good to dynamically configure installer during build, in SetupFactory we have to replace certain hard coded string tokens with dynamic configurations (like the version of current build)

I thought SetupFactory was pretty dynamic after what @andreievg achieved with the BAT file code.

> * It's only really Mark, Ujwal and Andrei that had any experience with SetupFactory, there was a comment from Craig that using SetupFactory would be good because we already have experience with it, I wonder if that's still true given the above. I think if we do explore different installer / bundler it would be good to consider simplicity of use vs functionality (ideally simple and with lots of feature).

@raviSussol  and Jonna has also worked on various aspects of setupfactory recently.  

My only concern is that new application means, more things to get used to and to manage. So potentially trouble shooting may take longer.  :-(

**Comment by andreievg** [comment]
@ujwalSussol thank you.

I guess we can get started with SetupFactory, since we know how to use it, and it sounds like more staff have experience with it than I thought.  We can always explore other options. And SetupFactory should be quick to get going.

**Comment by mark-prins** [comment]
One disadvantage of SF is that it is windows only - I created a linux build server so that we could build the android library, as I've been unable to do this on any other platform. Looks like we may need to make use of the current Jenkins server 😉

**Comment by andreievg** [comment]
We should consider what 'upgrader' look like (is it just binary replacement ?)

**Comment by mark-prins** [comment]
I'm not sure that we have many options for the upgrader, ideally this would be a smaller file - wondering if we can somehow reference a version of external dependencies and reduce the installer size that way. 

I'm thinking we just replace the binary, at least to begin with.

I wonder if SF handles dependencies and whether that can be used to create an updater?

**Comment by andreievg** [comment]
I think our release binary is quite small, and all dependencies are in one executable (40mb on Mac, will have to check Windows and Linux). So having it in upgrader shouldn't be an issue (i think only dependency would be postgresql binaries (100 to 200mb), which is postponed, otherwise upgrader would be the same size as installer)

**Comment by mark-prins** [comment]
🤔  I must be doing something wrong with the build - not sure how you're getting 40mb!

![Screen Shot 2022-06-13 at 6 46 25 PM](https://user-images.githubusercontent.com/9192912/173295824-5a41c851-61a6-4b38-b6b9-ed122e89f31c.png)

Looking a the builds on [google drive](https://drive.google.com/drive/u/2/folders/117AXnR0If3I_GD6fOW7CAkrH66-zB9PL) they're 210+mb.

**Comment by andreievg** [comment]
> I think our release binary is quite small, and all dependencies are in one executable (40mb on Mac, will have to check Windows and Linux). So having it in upgrader shouldn't be an issue (i think only dependency would be postgresql binaries (100 to 200mb), which is postponed, otherwise upgrader would be the same size as installer)

Hmm i just built again.. and it's 185mb oops, it compresses to something quite small though, not sure where i got the 40mb from.

**Comment by andreievg** [comment]
[By default, the Rust compiler optimizes for execution speed, compilation speed, and ease of debugging (by including symbols, for example), rather than minimal binary size.](https://stackoverflow.com/questions/29008127/why-are-rust-executables-so-huge)

Btw, it zips incredible well, so shouldn't be an issue including whole binary in upgrader:
![Screen Shot 2022-06-14 at 5 39 52 PM](https://user-images.githubusercontent.com/26194949/173501576-ef932505-db1e-42f3-80db-60f29e4ebb08.png)

**Comment by mark-prins** [comment]
the compression is impressive! I'd expect the installer to have a compressed version of the binary which would be an awesome install size

**Comment by craigdrown** [comment]
Can create service with SetupFactory
https://www.indigorose.com/webhelp/sufwi/Program_Reference/Services/Create_Service.htm

**Comment by raviSussol** [comment]
Hi @mark-prins @andreievg I've started working on this (particularly in the setup factory) and I was wondering if we have any defined folder file structure of the open msupply remote server application (for both client/server) or still to decide about it so that we can use them in the setup factory template to build installer. I have got some rough idea about folder/file structure while building and testing the project.

```
Open mSupply
|__ certs # stores ssl certs for the remote server
|__ configuration # stores yaml configuration files for the remote server
|__ data # stores sqlite datafile along with index and log files with it
|__ packages
      |__ host
            |__ dist # stores production built of the client project
|__ open_mSupply.exe # main remote server application file
|__ open_mSupply_cli.exe
|__ open_mSupply_report_builder.exe
```
The 2 extra `open_mSupply_cli.exe` and `open_mSupply_report_builder.exe` can also be put together inside the `bin` folder if we want to group them as per functionality for eg. cli tools.
```
|__ bin
      |__ open_mSupply_cli.exe
      |__ open_mSupply_report_builder.exe
```
Let me know what you think about them. I've also looked at building client/server projects on the windows and have been able to build on the windows successfully. For android, I've setup the project on the windows but haven't been able to build it yet. Had got some issues while building the remote server but still need to look at in the details - I'll check them later. Having said that, I believe we are targeting for the Windows and the Android platforms for the first phase?

**Comment by mark-prins** [comment]
Hey @raviSussol that's great to hear!

This is what I've manually installed on the servers so far:

```
C:\Program Files\open mSupply>

open mSupply/
├─ app_data/
│  ├─ certs/
│  │  ├─ cert.pem
│  │  ├─ key.pem
│  ├─ static_files/
│  ├─ settings_app_data.yaml
├─ configuration/
│  ├─ base.yaml
│  ├─ example.yaml
│  ├─ local.yaml
├─ log/
├─ remote_server.exe
```

with the `static_files` and `settings_app_data.yaml` being auto generated, and the `log` dir created using nssm which is redirecting std_err and std_out to logs. I've changed that in this PR though #504 - basically, just leave out the log directory.. that should be handled elsewhere!

We don't need `open_mSupply_cli.exe` or `open_mSupply_report_builder.exe` strictly speaking - but they might be useful. I also wonder about putting all of those in a `bin` directory, just to make it neater?

and.. android.. 🙄 yeah. I've had trouble building.
There's a linux server (build.msupply.org) that I set up to run the android build. I think you should ignore the android build for now - that's outside the scope of the installer anyway 😁

**Comment by raviSussol** [comment]
Thanks for the info @mark-prins. Regarding the `static_files` and the `settings_app_data.yaml` files being auto generated - I tried to build client and server individually as well as all at a time both but couldn't see those folder/files in the project after build completed. Is there any extra steps need to be done for them?

Also looks like the `static_files` contains report html forms if I'm not mistaken? Wondered how we serve frontend app or where the production built frontend app is stored. Does this folder also contain the production build frontend app files?

Regarding the nssm is it appropriate to handle file I/O via external application rather than handling inside our own remote server? I also saw few discussion in #504 about the different file log crates but handling the logging by our own app - wouldn't be better and reliable? Furthermore, that would remove the extra dependency plus the other reason that the nssm come in use is to create and configure the open msupply as a service which I think can be achieve by the setup factory's service management script (also mentioned by @craigdrown above).

**Comment by mark-prins** [comment]
The `static_files` and the extra `yaml` file are created at runtime - basically, don't worry about them 😉 
what I should have said is that you don't need to create that directory in the installer. or the logs.

Quite right - the static_files is just for the reports. The front end is actually embedded in the server binary, so there aren't any external files required for that.

And we won't need nssm anymore. I needed it to create the windows service ( but that can be done with setup factory ) and to capture stdout messages to file and rollover the logfiles. Which we don't need now - with the logger as part of the server.

So.. in summary:

- create install directory, after asking the user. Defaults to `C:\Program Files\open mSupply>`
- create the directory structure below
- copy the yaml files, and `remote_server.exe`
- create a windows service using setup factory ( should be set to start automatically, possibly after a delayed start 🤔  )

```
open mSupply/
├─ app_data/
│  ├─ certs/
├─ configuration/
│  ├─ base.yaml
│  ├─ example.yaml
├─ remote_server.exe
```

**Comment by mark-prins** [comment]
Another question is whether we make the installer for postgres or sqlite. 
I've only needed the postgres version so far, so that's what I'm most interested in. For people to try open mSupply themselves, they'd probably want the sqlite version though. 

Either we have two separate installers, or have a bigger installer which asks you. I like the second option.. but maybe the first is easier? Might be better for now?

**Comment by raviSussol** [comment]
@mark-prins I think we can provide options for different databases setup in the installation wizard while installing. Maybe 2 radio buttons saying,

Setup with:
- [x] Sqlite
- [ ] Postgres

_Just used checkboxes here to demonstrate but would be radio buttons in actual._

 By default we select the sqlite database and if customer chooses the Postgres then clicking `Next` would allow him/her to download the Postgres db and then installation process starts for the Postgres.

This way we don't have to build 2 separate installers and potentially can reduce installer size for the Postgres setup allowing them to download at runtime.

**Comment by mark-prins** [comment]
Thanks @raviSussol sounds good!

**Comment by raviSussol** [comment]
Hi @mark-prins, Hi @craigdrown I think we might want to update the license and warranty text for a user to abide agreement for the open msupply software as compare to our mSupply product? If yes then I'd need the new license and warranty file for suf installers.

**Comment by mark-prins** [comment]
yes we will, thanks @raviSussol 
For now, just use the mSupply one.. we're reviewing the license for open msupply, so will write up something
