### ISSUE TITLE
Clicking OK on a single line in a stocktake changes all the other ones to be counted as well 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#2226]
## What went wrong? 😲

Louisa found that when you click OK on a single line in a stocktake, it changes all the other ones to be counted (and be in black font) as well   

https://github.com/openmsupply/open-msupply/assets/29744386/9c6d51e3-d09d-41a4-a7f1-28afb7f4e242

## Expected behaviour 🤔
I would think it should only affect the one that was clicked

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Create a new stocktake with placeholder lines (eg. from a location or masterlist) 
2. Click on one line
3. Click OK 

## Your environment 🌱

 - Version: 1.3.0
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one) - Chrome, reproduceable on demo server 
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by CarlosNZ** [comment]
Looks like it's just a front-end issue (it's not changing any actual data). I'll have a quick look at this this afternoon, but if I haven't fixed it by the end of the day I'll unassign myself if someone else wants to look at it later in the week.

**Comment by CarlosNZ** [comment]
Okay, haven't been quite able to fix it, but this is what I found so far for anyone else who wants to take a look:

The problem is that the `useHighlightUncountedRows` hook in `ContentArea` is not triggering its `useEffect` when the `rows` don't change. And that's the case when you just click "OK" without changing anything. Something else is causing the row state to "reset" (which sets the colour to default black), but it only gets re-reset (to highlighted placeholders) when actually *changing* a row as the `useEffect` in `useHighlightUncountedRows` is triggers (which runs `setRowStyles()` on the placeholder rows).

So, to fix, we either need to:

- somehow get `useHighlightUncountedRows` to re-run its useEffect (probably not that easy, as the `rows` really aren't changing
- figure out what's causing the row state TableStore state (`in useRowStyle`) to get reset and prevent this (preferred)
