### ISSUE TITLE
Last Sync date isn't updated properly after some system date changes

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#2263]
## What went wrong? 😲
The `Last Sync` doesn't get updated at all if I'm ever to change my system date for some reasons, and the sync button keeps loading forever. Thankfully, sync is woking fine though; just a problem with the UI!

## Expected behaviour 🤔
I know this ain't any regular case (changing the system date to some future date; I happened to do so for some testing purpose), but change of dates shouldn't lose that `Sync now` button as well; it literally keeps loading forever ever since the date was changed! 

## How to Reproduce 🔨
What I did somehow:
1. System date was changed to some future date
2. Back to oms, created some records
3. Synced.
4. Saw the error: it keeps loading forever, but thankfully the records were synced successfully. The `Last Sync` also updated ever since:
<img width="714" alt="image" src="https://github.com/openmsupply/open-msupply/assets/59193490/3b9d9aa8-b103-427f-a0d0-4f5aa15089a5">

## Your environment 🌱

 - Version: v1.3.00 exe
 - Platform:
   - [ ] android (tablet)
   - [x] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

**Comment by fergie-nz** [comment]
Hi @nisha-dangol, I'm able to recreate this in a slightly different way than you described. Is this how you triggered the endless loading?

1 - set the system date to future
2 - make a sucessful mannual sync
3 - set date back to present
4 - sync ui now continues forever.

I can see that there is a hook in Sync.tsx which sets loading to false based on a changing last_successful_sync of the logged in user. This won't change, however, because the most 'recent' sync was in the future which will be unaffected by adding new sync data in the present.

I am wondering if we could fix this by changing a users last_successful_sync datetime to be the latest successful sync datetime which is earlier than the current datetime, however I also wonder if this might introduce other unforseen issues.

I also can't think of a case where this would cause an issue - unless someone flew through timezones and quickly sync'd again?

I wonder if we can close and/or triage this issue as low priority given that:
- It is very unlikely to occur without timezone travel and/or system date manipulation
- It is a front end issue only and can be fixed by refreshing the page

**Comment by fergie-nz** [comment]
Actually I've just though of a very simple fix to stop the eternal loading at #2301

**Comment by mark-prins** [comment]
Triage: decided it was edge case enough to close
