### ISSUE TITLE
No alert when rounding on allocation in dispensing and outbound shipments

### ISSUE THREAD

**Issue by fergie-nz** [openmsupply/open-msupply#2266]
## What went wrong? 😲
When allocating medication in outbound shipments or dispensing to patients AND rounding up, there is no UI indication for the user.

https://github.com/openmsupply/open-msupply/assets/90807420/5efd24b0-786b-4b23-a83c-b474616ce532

## Expected behaviour 🤔
It would be nice to have some way of showing that the amount dispensed is not what was requested.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Dispensary' > 'Prescriptions'
2. Add an item which only has pack sizes greater than 1
3. Attempt to issue a number of medicines which is not a multiple of pack sizes ie 1
4. Allocate
5. See that the total quantity != requested issued AND there was no warning/alert/prompt

**Comment by CarlosNZ** [comment]
Related to this -- we also noted that for Prescriptions, we will need a way to issue partial packs. Something for later perhaps, just noting for now in case it relates to how this issue is dealt with.

**Comment by nisha-dangol** [comment]
Tested in v1.5.03 apk and exe. 
I do see the alert/warning message for different packsize is chosen instead of desired/chosen quantity like below:
<img width="990" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/b0caf77e-2bc0-43f4-aec6-de523fb72145">

@fergie-nz @mark-prins 
..but I also notice another issue of not letting us choose the exact issue quantity (like quantity starting from 1) when there are different pack sizes available. Issue details here: #2727
