### ISSUE TITLE
Sensor detail view

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2286]
## Describe the solution you'd like 🎁
Note from meeting: Change to a modal
- Header: Edit Sensor Details
- Hook to update sensor
- Left side: 
   - Sensor Name: only editable if name does not exist
   - Storage Location: Dropdown to add location (add a NONE option)
   - CCE (Read-only and empty for now)
- Right side: (Read-only change of design: just text not grey-on-grey disabled text field)
   - Serial number
   - Battery level
   - last temperature recording value
   - last recording date / time: explore possibility to show "number of hours (or days) since the last records", we could implement an alert if no record for more than X hours (or day) in the future (not for this version)

Mock up: 
![Screenshot 2023-10-12 at 11 58 16](https://github.com/openmsupply/open-msupply/assets/61820074/3c39e1a5-b739-45a1-8cbb-5db60f8b480d)

### Estimate
3 hours

### Moneyworks Jobcode 🧰
OMS:COLC

**Comment by richardmoizeau** [comment]
> * CCE (Will be a dropdown list but have to wait for asset integration) for now just display whatever is in the database

most likely a mistake from the design but we won't assign an asset to a sensor but to a location. However, this could be a read-only field derived from the location (if the location has a linked asset).

**Comment by adamdewey** [comment]
Yeah agree, would be nice to show a linked asset via the location association

**Comment by mark-prins** [comment]
After discussing:
- ok to have the disabled fields as the standard, plain text, rather than a disabled input
- The ability to add location would result in modal-on-modal for stocktakes, stock and inbound shipments
- Add `None` to the list of location options, and remove the unlink location button
- can change to a modal, once the 'add location' function is removed
- CCE is read only, as that is a link via location. Move it to the RH side (read only items)
