### ISSUE TITLE
Stocktake : Modifiable stocktake date

### ISSUE THREAD

**Issue by Pauline-mSupply** [openmsupply/open-msupply#2289]
## What went wrong? 😲

When creating a stocktake, before finalising it, there is a field : stocktake date that can be modified, which means that I can do a stocktake dated in 2017. Having two dates fields : _Created_ and _stockate date_ is a little confusing. 
It would make sense to prevent backdated _stocktake date_.

## Expected behaviour 🤔

1. Stocktake date cannot be edited OR 
2. Stocktake date can be edited depending on user's profile AND/OR
3. Stocktake date can be edited but cannot be in the past

## How to Reproduce 🔨

Create a stocktake and change the filed stocktake date 

![Screenshot 2023-09-26 at 2 54 26 PM](https://github.com/openmsupply/open-msupply/assets/114633283/b9ce0980-6a35-4002-8739-a3a4c25fb044)

## Your environment 🌱

 - Version: demo-djibouti server
 - Platform:
   - [ ] android (tablet)
   - [X] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)
 
### Agreed solution 
Disable the stocktake field for now

**Comment by Pauline-mSupply** [comment]
I just saw that this was a permission in mSupply, is it applicable to Open mSupply ?

**Comment by mark-prins** [comment]
it is a valid usage, to set the date in the past. You may have done a stocktake on paper and are now entering the data, in which case you set the date to be the date of the stocktake and not the current date.

That may of course be problematic.. if transactions have happened since the stocktake, the numbers might not be right now.

And yes, in mSupply the user needs to have the `Edit stocktake date` permission. 
We are not mapping that currently in omSupply

**Comment by Pauline-mSupply** [comment]
Thanks Mark !

**Comment by fergie-nz** [comment]
@Pauline-mSupply are you happy if I close this issue now?

**Comment by Pauline-mSupply** [comment]
Yes ! Thanks a lot

**Comment by roxy-dao** [comment]
Did we want to implement the edit stocktake date permission?
