### ISSUE TITLE
Document permissions

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#29]
There are two permissions required to access a patient document:
- [ ] Patient access: user must have access to patient the document belong too
- [x] Document type access: user must have QUERY and/or MUTATE access for the document type

## Patient access:
In a first step we assume the user only has access to all patients at stores the user has access too.
The name_store_join table can be consolidate to find out if a patient is available at a store.

How to find out which document belongs to which patient?
There are three options:
- ~~introduce a patient_document_join table~~
- ~~just by document name, e.g. by convention patient document names already starts with the patient id~~
- store patient id on document table as an optional column (this comes at the cost that the document table becomes somewhat patient specific) Or better call it document `owner` which is more generic.

- [x] #590 
## Document type access
A new table is needed to store document type permissions.

- [x] #593 

# Protecting Endpoints
- [x] Ensure that the document_registry endpoints only returns document types the user has access to
- [x] Check permissions on mutation/query endpoints

**Comment by andreievg** [comment]
Just a note: And I think the initial comment describes this, in one of our meetings we mentioned that program visibility should be   controlled by user permissions (vs just. associating them with store).
It sounds like it would have to be a customer permission (since programs are 'dynamic'). I don't think this fits with our existing permission schema (since they are boolean and static values), would assume we would need a new way to associate a user with program/document on central server. As for remote server, we would probably need to have program_id in `user_permission` ?

Alternative is to have `static` and predefined programs and add booleans for them in central.
