### ISSUE TITLE
Export and Import initialisation

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#54]
To remove reliance on mSupply central initialisation while developing, it would be good to have functionality to export and import initialisation from/to file. This was mainly done in docker build work, but removed, can be reinstated.

**Comment by Chris-Petty** [comment]
@andreievg maybe not just now, but in the near future it'd be quite easy to dump sync initialisation from server into a JSON file. I imagine it'd be pretty easy to read that JSON into the buffer and integrate it as per usual?

**Comment by andreievg** [comment]
> I imagine it'd be pretty easy to read that JSON into the buffer and integrate it as per usual?

Yeah the PR is doing just that

PR also user v4 login to get user info and store it in the export (something that might be a bit more tricky if the server does the export ?). 

It was very easy to use existing abstraction in remote server to export central pull, remote pull and users to JSON (instead of central server doing it)

**Comment by Chris-Petty** [comment]
So you're doing an initialisation from the central server, but just pumping it into a JSON instead of into the DB? Which can imported again later on fresh DB? Neat!

Central server would put all user's that can login into the JSON - you might get a bunch of cruft remote-server currently ignores. The current export also inserts the `[site]` record as the first record in the file, including server URL but with the password removed.

I toyed with making the central server make JSON export instead of the XML export last year just to see how big a difference it'd make. The output file was literally 10x smaller and the export was waaaaay faster, and it was super easy haha. I think it could be a good value low hanging fruit for v6.2 Central (i.e. not this release but the next).
