### ISSUE TITLE
[prog][control] Show enum + description

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#598]
Goal: Control that is able to select a value based on code and shows an description:

![Image](https://user-images.githubusercontent.com/88299195/189244385-4b4ea818-35f5-42a3-9f50-60431eb055a0.png)

Current json schema definition, i.e. enum + description:
```typescript
enum ARVRegimen {
  /** TDF + 3TC + DTG */
  New1a = "1a-New",
  ...
}
```
Happy to use other data representation but enum seemed to be fitting.

The enum descriptions might also be handled similar to #370 by putting the description into the ui schema.

**Comment by clemens-msupply** [comment]
@richardmoizeau do you have an opinion on it?

**Comment by richardmoizeau** [comment]
Since we are talking about the drugs being dispensed. I think we need to start thinking ahead about when we will generate a list based on the catalogue (not the stock available since you can prescribe an item even if you don't have stock). They should only be items that are flagged as "ARV" medications though. I just the PNG stakeholder to see if we can have a dedicated meeting for this section.

**Comment by clemens-msupply** [comment]
Yes that would be cool, to be able to flag an item! (even though there might be technical challenges if a medication can have multiple flags)

My question was more technical though, i.e. should we implement a control that shows the code + description in a drop down like in the screenshot or is there an alternative?

**Comment by richardmoizeau** [comment]
I was thinking something like the one we used for adding an item to a shipment. You can type the code or the name or simply navigate through the list. 

![Screen Shot 2022-11-23 at 11 08 08 AM](https://user-images.githubusercontent.com/74992958/203431322-183de8f6-e858-492c-9ea8-a3e4507a64e2.png)
