### ISSUE TITLE
Consolidate progress status and other steppers

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#649]
https://github.com/openmsupply/open-msupply/pull/640#discussion_r980467067

**Comment by mark-prins** [comment]
Thanks - I was thinking of a few other changes to the initialisation stepper. Perhaps this is the place to put them?

- I doubt that the individual sync steps are of much meaning to normal users: so was thinking that a standard progress indicator could be more useful. Not sure that this is exactly possible - do we know the total count of each step prior to reaching that step? I'm reluctant to remove the stepper though, as that is very neat.. so am wondering about a total progress indicator as well as the stepper. Just a [linear determinate progress indicator](https://mui.com/material-ui/react-progress/#linear-determinate) to show how far through you are
- the screen is now a bit too busy.. too much on it, and inconsistent spacing around elements. We don't need the progress indication until sync is in progress though, and the other fields are all disabled when syncing.. so I'm wondering about swapping out the form section, and only show the progress indication when syncing. only show the form when it is enterable. that gives us a lot more space to play with
- there's some jumping around of elements due to the height changing, for example when there's an error. this would be easier to resolve if the progress had more room

**Comment by andreievg** [comment]
> and only show the progress indication when syncing

I think on failure, it's good to see what the url and site name was, I think it's worth keeping (like we do in mobile, except ofcourse not editable)

> much meaning to normal users

I think:
* The most likely audience for initialisation is TMF
* For normal users if they have trouble with sync, and they contact support, the more they information they can see the more details they can provide to support the better
* I also think it's good to show how many records of each type have been synced during sync iteration, would the replacement progress bar show this ? 

> there's some jumping around of elements due to the height changing, for example when there's an error. this would be easier to resolve if the progress had more room

Sound great. Would also point out that there is existing jumping when error occurs before progress (between initialise button and form)

> Just a [linear determinate progress indicator](https://mui.com/material-ui/react-progress/#linear-determinate)

I don't think this is enough, we have a lot of support requests (internal and external) due to sync, and we ended up adding more information to original mobile sync indicator, for that reason I think we want to show as much info as possible.

**Comment by mark-prins** [comment]
fair point about 'normal user' and the audience for sync. and the need for detail!
Agree that it's good to have the number of records of each type 

might have to look at the existing jumping too.. 🤔  not now though! that's just a general thought..
