### ISSUE TITLE
Bootstrap mode open issues

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#66]
- [ ] How to handle sync settings in the config file? e.g. does the config file always overwrite settings in the DB?
- [ ] Related: Remove sync settings from config file? but this would be inconvenient for automated deployment -> some cli args to provide settings in first startup?
- [ ] Once the initial sync started disallow making fundamental sync setting changes, e.g. no site_id change
- [ ] Move server status out of the server settings endpoint into a general "status" endpoint (unify with apiVersion endpoint?). This endpoint could also provide current sync progress details or similar information.
- [ ] Have the "status" endpoint available during initial sync to report the sync progress, i.e. introduce another server state: BOOTSTRAP | INITIAL_SYNC | RUNNING
- [ ] In the code, rename stage0 to bootstrap

**Comment by andreievg** [comment]
> How to handle sync settings in the config file? e.g. does the config file always overwrite settings in the DB?

I think we should only use config file if database settings are not present and it's ok to panic on startup if config file sync settings don't match db sync settings. If we allow overwrite of db setting from config file we could sync more than one site causing conflicts and confusion for developers.

> Related: Remove sync settings from config file? but this would be inconvenient for automated deployment -> some cli args to provide settings in first startup?

We've never done auto deployment, I think it's sufficient to install remote server and then configure it via initialisation UI (it would also be easier to retry and cancel initialisation in case of errors). But the config file or env var are useful during development, so I think we should keep them.

>  Once the initial sync started disallow making fundamental sync setting changes, e.g. no site_id change

Btw site_id is not needed as a configurable setting, I think the plan was to do what mobile does and use /site endpoint to both confirm sync settings are correct and to get site_id.  I think for now we can allow for things like interval, batch size and sync site password to be configured after initialisation, but I think this needs to a complete seperate end point. (and we can make another issue for changing url and maybe sync site name, those are dangerous so would need to think about them in depth)

> Move server status out of the server settings endpoint into a general "status" endpoint (unify with apiVersion endpoint?). This endpoint could also provide current sync progress details or similar information.

Agree, I think it's great to have a sync status/info endpoint, proposal below makes it a bit more granular (once again to fit with Mobile way). From my understanding it's been very beneficial to have more granular sync information presented to the user, as it's one of the areas that is pretty complex, in case of issues it's good to have descriptive indication of errors.

I think it would be pretty easy to implement subscription to sync state, but not required for now, front end can do polling.

> Have the "status" endpoint available during initial sync to report the sync progress, i.e. introduce another server state: BOOTSTRAP | INITIAL_SYNC | RUNNING

Hmm, I think front end needs to know about these states: Initialisation:NotStarted, Initialisation:Started, Initialisation:Error, Initialisation:Completed. And server needs to know about Initialisation:Completed (or not), to show the correct schema.

> In the code, rename stage0 to bootstrap

I think it's clearer to developer if we are more specific about the 'stage' as per above comment (bootstrap means many different things, and it's not very clear what that stage represents). Also our devs are already used to initialisation terminology

# Full Spec for Initialisation and Manual Sync

[Diagrams below in drive](https://app.diagrams.net/#G1cbxpYgSodYAv5DkcvAox9TZYRM_KVMmX)

`Disclaimer` We've been talking about simplicity a bit lately and the logic below might seem quite involved. I think that's the simplest way to fit with below requirements (from user perspective diagram), although diagrams have quite a lot of moving bits, they are pretty detailed, so for any argument of complexity please consider the fidelity of detail in the diagrams. (and the reason for such granularity was to easy implementors job and to use these diagrams in dev docs, I think we should be doing a lot of diagrams for dev docs and for specs/design) 

I've tried to outline what I think an 'ideal' sync flow should be, based on requirement to replicate Mobile:

## From User Perspective

![Screen Shot 2022-06-09 at 12 18 26 PM](https://user-images.githubusercontent.com/26194949/172738515-c8fdf621-3162-4206-b7ce-65129a949cb0.png)

### Initialisation Requirements

* When app first starts user can only see initialisation page
* When user enters initialisation details and proceed to initialise they should be informed if server and credentials are correct straight away
* While initialisation is in progress user should see the progress (record preparation, central pull and remote pull status with number of records synced or awaiting sync and any errors)
* If server is restarted during initialisation it should resume initialisation (shouldn't need to restart initialisation)
* If there is an error user should be able to retry or cancel initialisation

### Manual Sync Requirements (Operational)

* User should be able to see last sync status (central pull, remote pull, remote push with number of records synced or awaiting sync or any errors and time of operation)
* User can see how many records are in sync queue
* User can see how long till next sync (maybe not required?)
* User can force manual sync, and observe it's progress (similar to initialisation progress)

I think the following should be implemented to meet above requirement:

## Front End and Back End Interactions (Initialisation)

![Screen Shot 2022-06-09 at 12 21 19 PM](https://user-images.githubusercontent.com/26194949/172738719-f63c4a25-c7ac-45a9-b974-6b1fb9b28e73.png)

* Not sure yet if we should implement subscription (by subscribing to change log) or just poll from front end for now
* useSyncSate.waitingForSyncUpdate needs to be done because SyncState updates are done on back in within sync thread, and most api operations just trigger an operation on that thread (so we can't give an immediate new SyncState in response to those API calls)

## Graphql Schema

This is for Sync State Info only,  mutations should be self explanatory (initialisation, retry, cancel, manual sync).

I tried to reduce optionals thus the union for status.

[Use this branch ](https://github.com/openmsupply/open-msupply/compare/initialisation-graphql-schema)if you want to see the schema (it's bootstrap mode schema, so no sync settings in config and empty database would show it)

![Screen Shot 2022-06-09 at 12 29 35 PM](https://user-images.githubusercontent.com/26194949/172739449-e56cff40-89ec-4847-b619-054f4aac5bd7.png)

## Back End Logic

All of the setting and getting of sync info is through a server.

![Initialisation and app startup-Page-2 drawio](https://user-images.githubusercontent.com/26194949/172739938-7464cd76-6a73-4a6d-a8ec-d0f0c2f75a4a.png)

I am actually not sure why we would want to have different schemas loaded:
* It's easier to codegen the whole schema for f/e types 
* There is only one end point that will need to be disabled during initialisation (the login end point, all others are protected by token)
* I don't think it's a sound practice for front end to be 'controlling' the server (restarting etc..)
* If we do need to load another schema, I think it's better to do with with RwLock on schema, here is an example
[graphql_schema_swap.zip](https://github.com/openmsupply/open-msupply/files/8865793/graphql_schema_swap.zip)

## Manual Sync

Not quite in scope of the issue, but had to consider how this would work with the same mechanism

![Initialisation and app startup-Page-3 drawio](https://user-images.githubusercontent.com/26194949/172740467-4d466881-c1f5-4be7-9a29-cdb06321a8f6.png)

TODO seek agreement or alternative solutions
TODO break down into tasks

**Comment by andreievg** [comment]
I realise that trying to implement this partially without full refactor as per design above would be very challenging, I had a little further, more details things about next steps, and realised we can simplify the logging a bit:

* We don’t need error for every step, just overall error
* In that case way simpler to just use one row for whole sync status (and insert. new sync status log every time we start syncing)
* Need to try and keep sync logic as clean as possible, so a low profile logger is best

```sql
CREATE TABLE sync_log (
id TEXT NOT NULL PRIMARY KEY,
start_datetime TIMESTAMP NOT NULL,
done_endtime TIMESTAMP,
prepare_initial_start_datetime TIMESTAMP,
prepare_initial_done_datetime TIMESTAMP,

push_start_datetime TIMESTAMP,
push_done_datetime TIMESTAMP,
push_progress_start INTEGER,
push_progress_done INTEGER,

pull_central_start_datetime TIMESTAMP,
pull_central_done_datetime TIMESTAMP,
pull_central_progress_start INTEGER,
pull_central_progress_done INTEGER,

pull_remote_start_datetime TIMESTAMP,
pull_remote_done_datetime TIMESTAMP,
pull_remote_progress_start INTEGER,
pull_remote_progress_done INTEGER,

integration_start_datetime TIMESTAMP,
integration_end_datetime TIMESTAMP
)
```

Above would make it a lot easier to insert and calculate.

I don't think we need to differentiate sync log by operation or initial, it's quite easy to deduce if it's initial by looking at sync log and seeing if there are any rows with done_datetime is not null.

Lastly the graphql schema would be a bit different: https://github.com/openmsupply/open-msupply/compare/initialisation-graphql-schema2

And we really want to keep the `sync` code clean, so the logger would need to be low profile, here is an example of what i am thinking: https://github.com/openmsupply/open-msupply/compare/feature/sync-v5...Sync-logger-example

**Comment by clemens-msupply** [comment]
Why do we need these exact times in the table? can't we just log strings and have a single row in the key value store to track the current state?

**Comment by andreievg** [comment]
@clemens-msupply 

> Why do we need these exact times in the table? can't we just log strings and have a single row in the key value store to track the current state?

We would want to display progress in UI, at the very least what mSupply mobile shows. Please see `Manual Sync Requirements (Operational)` above.

For key value store track of current state, what would it look like, would you need to clear key value store values before every sync ? How do we deduce sync step progress for display in UI ?

**Comment by clemens-msupply** [comment]
Ok I see, can we keep this information in memory though? or do we need to persist information about the last sync? since we sync at startup this may not be needed?

With the key value store I just meant to keep track if we did the initial sync (as we do now).
