### ISSUE TITLE
'Server Error' on login for recently setup android device

### ISSUE THREAD

**Issue by jmbrunskill** [openmsupply/open-msupply#670]
Related to #669

After setting up and syncing a new android device, after  sync appears to have finished on the server side, login fails with an generic 'Server Error' message on the client.

There are no requests received on the central server to validate the password.

Since there were a lot of records in this sync site (~50,000) it could be that the site records are still being 'integrated'?

After waiting a few minutes more login starts working.

**Expected behaviour**
- More informative error message or logins should succeed during integration (if indeed that is the issue)

**Comment by Chris-Petty** [comment]
Building on the ideal solution for #669 that is a initialisation progress bar, I'd say that if this problem is indeed the integration, that progress bar should be:
- 1/3 waiting for server initialisation
- 1/3 pulling central records, pulling queued records (these can say how many are in central_log and progress, queued records and progress) (tangent - any reason not to pull central_log while initialisation above is running?)
- 1/3 integrating records detailing how many records have been integrated out of the total.

**Comment by andreievg** [comment]
This should be done with: https://github.com/openmsupply/open-msupply/pull/640, which will be merged with https://github.com/openmsupply/open-msupply/pull/679
