### ISSUE TITLE
Catalogue, Customers, Suppliers : put code before name in the table

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/open-msupply#833]
![image](https://user-images.githubusercontent.com/29744386/205811776-b6857171-1802-4256-a6b0-625bd56f012d.png)

Swap the columns around :)

**Comment by DhanyaHerath** [comment]
Agreed! 
Also, masterlists probably don't need the `Code` column right? They don't have a code afaik. 
I would say this is low urgency, but maybe nice to do before deploying too many places so that people don't get confused by the UI change. 

![image](https://user-images.githubusercontent.com/29744386/205811889-1d62fcb5-0df7-4049-8719-ddf19de7fe08.png)
