### ISSUE TITLE
Stocktake reasons

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#870]
When editing a stocktake, if the quantity entered is different from the actual quantity and [options](https://docs.msupply.org.nz/preferences:options) are enabled then the user should be prompted to select a reason for the adjustment. For example, this is how it looks in mobile:

![image](https://user-images.githubusercontent.com/9192912/211678073-56b17d64-5eeb-4b0c-8811-d5ffbac913dc.png)

see the [mobile documentation](https://wiki.msupply.foundation/en:mobile:user_guide:stocktakes#if_prompted_enter_a_reason_for_inventory_adjustments) for details

**Comment by mark-prins** [comment]
Also, when reasons are included - update the default stocktake query so that reasons can be added to the print template

**Comment by roxy-dao** [comment]
Mentioned in #1028 too (I think?)

**Comment by mark-prins** [comment]
kinda - this issue is for an enforced reason, which is selected from a list. The user is forced to both

- enter a reason before saving
- select from a pre-defined list

The functionality in 1028 is for comments per stocktake line, which can also be used to explain the reason, but is less restrictive 😉

**Comment by roxy-dao** [comment]
@andreievg 

Currently mSupply allows you to config the reasons in `Preferences` under `Options` and the `id` of the `Option` is saved in the stocktake line. Reasons are mandatory on both mSupply and mobile. 

1. Should the mSupply option table be synced to omSupply or should a new table be created?
2. Should reasons always be mandatory?

**Comment by andreievg** [comment]
My intuitive feeling toward this is a table called [inventory_adjustment_reason] and [invoice_line].inventory_adjustment_reason_id, the new table with [type] fields (addition or reduction) and text field for the actual reason and perhaps enabled/disabled field

> Should the mSupply option table be synced to omSupply or should a new table be created?

I think we should try to use as much of existing configuration UI as possible. So I think either way we would keep the structure in mSupply, we can translate to a more desirable omSupply structure. Also want to keep existing mSupply reasons

> Should reasons always be mandatory (if enabled)?

Could they be for now ? And maybe we can add an option by store or global to have them mandatory (store_preference, global_preference).

Just something to be mindful off, some use cases and UX questions below (maybe we can discuss them in standup):

* How to make sure the reasons are mandatory ? During finalisation ?  Indicate in UI that reason should be chosen ? (keeping in mind it should really be done on both f/e and b/e) 
* Should only be mandatory if reason is defined for the `type` (reduction/addition), this would mean reason `clears` if counted changed from say reduction to addition (and reduction reasons exists but addition reasons don't exist)
* If both types are mandatory and counted is changed from one to the other, do we `clear` reason and indicate that reason is still required ?
