### ISSUE TITLE
KDD: Document Sync Design (2022-06-03)

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#88]
_Date_: 2022-06-03
_Deciders_: Andrei, Clemens
_Status_: PENDING
_Outcome_: PENDING

## Document Object Sync (central <-> remote)

The central server needs to know which sites are interested in which documents.
In the following its assumed that all currently used documents are associated with a patient and can be associated to a site by the patient id.
For example, `name` are mapped to `stores` (and thus to a site) using `name_store_join`.
This means the central server can figure out which document versions need to be pushed to which site.  

## Merge
**Single site merge:**
For concurrent edits on a single site we can enforce a somewhat linear edit history.
For example, when two UI users `A` and `B` do concurrent edits of the same document version `v1`:
- A commits `v_A` first
- B tries to commit `v_B` but server detects that `v1`, which `v_b`is  based on, is not the latest version anymore
- Server does an auto merge of `v_A` and `v_B` and proposes the merged version to B
- B accepts this version (or changes it if desired) and commits this version

**Multi site merge**
If changes happen concurrently on different sites there are multiple document heads.
The easiest approach is to do an implicit merge of all these heads when querying a document.

Note: is single site merge needed then?

There are two merge strategies proposed:

### Merge option 1: Diff changes
Every document change is recorded as a diff to the previous (latest) version, e.g. 
```typescript
{
  timestamp: ...,
  added: {
    value1: true,
    obj: {...},
  },
  removed: [
    ["obj1", "field1"],
    ["value1"]
  ]
}
```

``` rust 
let changes = sorted_list_of_all_diffs();
let merged = apply_all_diffs_in_order(changes);
```

_Pros:_

- easy to understand 

_Cons:_

- lookup performance when applying many changes?
- relies on storing diffs (less room for later optimizations)
- harder to apply custom merge strategies, e.g. if array merges are needed

### Merge option 2: Three way merge
To merge two document versions "their" and "our":

```rust
let (their, our) = get_heads();
let base = common_ancestor(theirs, ours);
// do a three way merge (or a two way merge if no base is found, e.g. theoretically possible to start without common base)
let merged = merge(base, theirs, ours);
```

_Pros:_

- standard/ proven algorithm used in version control systems like Git, hg, Fossil...
- more flexible storage layer, e.g. a document version can be stored as a snapshot or as a diff to previous snapshots
- faster lookups and scalable (if having many changes to a single document)

_Cons:_

- more involved algorithms (see below)

#### Common ancestor algo:

![Image](https://user-images.githubusercontent.com/88299195/171769389-0f720c46-b3ac-41f3-8fc8-911c647d1886.png)

1) Find all docs reachable from `our` version (green)
2) Follow `their` version history (blue) till encountering a common `base` doc
3) Detail: follow the latest documents in the hope to find a common ancestor faster
#### Three way merge algo:

![Image](https://user-images.githubusercontent.com/88299195/171772136-52e19b21-9e48-4a53-b34b-4d6e6afeb88a.png)

1) Collect all keys from `ours`, `theirs` and `base`: `["value1", "value2", "value3", "value4"]`
2) For all these keys check if the corresponding field has been added, removed or modified in `theirs` / `ours` (relative to `base`)
   - If no change -> take existing field
   - If mutation only happened in `ours` OR `theirs` -> apply changes from the mutated doc and continue to next field 
   - If mutation happened in `ours` AND `theirs` -> use solve strategy, e.g. "TakeChangeFromLatest" (ours in example) to resolve conflict
3) If object contains nested object apply algo recursively

## Where to merge and do reporting?
A merge of all data is needed to:
- do a global patient lookup for all sites
- do reporting using data from all sites

### Option1: Merge on central server
Once a remote site pushed its changes to the central server, the central server does an automatic merge of all patient data and updates the patient (name) table.
Similar other document data can be merged for reporting reason

_Pros:_

- to lookup a patient the central server just needs to look at the merged name table

_Cons:_

- central server has to know how to merge
- more 4d code
- extra work for the central server (performance problem?, especially for reports) 

### Option2: Merge on remote server site

Each remote site maintains its own list of patients which is created by merging all patient documents.
This list includes only patients that are known by a site.
Each patient has a site specific row (uuid per site).
This means that when pushing patients to the central server the same patients from multiple sites will not overwrite patients from other sites.
This also means a patient may have multiple rows on the central server; one for each site the patient is known at.
This allows the central server to do a global patient lookup.
For example, if two sites have the same patient there would be two rows on central, one for each site:

| row_id | site | patient id | patient name | ...|
|---|---|---|---|---|
| rowa | A | patient1 | myname | ... |
| rowb | B | patient1 | Myname | ... |

It's possible that both rows temporarily differ as in the example above but they would eventually be the same (except `row_id` and `site`) once both sites are fully synced. 

For reporting, there is a special reporting site which receives all required data from the central server to do the reporting.

_Pros:_

- central server stays simple and only needs to handle "find patient" queries
- central server only needs to handle sync -> lower performance requirements
- reports are handled on a dedicated site and doesn't affect the central server

_Cons:_

- Some duplicated patient rows on the central server
- extra report site needed

**Comment by jmbrunskill** [comment]
Do we have a strategy planned for how to transition off the 4d central server?
Feels like **Option2: Merge on remote server site** would be most natural but feels like a shame to implement in the old code base.
Could this be a good candidate offload from the central 4d application via a local API or something?
Do we also need to merge locally in remote server for some scenarios? E.g. would we be implementing the algorithms twice?

It's not clear to my what Option2 required duplicate patient records? Couldn't it be duplicated documents instead? I don't understand the full scenario so might be asking something silly :)

**Comment by andreievg** [comment]
Would like to start with the requirements as far as I can tell (not all of these are related to sync, but I think it's full spec):

* Able to edit same patient details concurrently on different sync sites
  * Avoid changes to field A overwriting changes to field B  
  * Latest changes takes priority (i.e. concurrent change to the same field)
* Able to enter arbitrary data for patient (and change it i.e. if mistakes were made or patient info has changed)
  * Aggregate type (one instance of form/data per patient i.e. patient details)
  * Tracker type (multiple instances of form/data per patient i.e. encounter)
  * Able to configure above form inputs and data shapes
  * Able to re-configure above form inputs and data shapes
* Record all changes for above by (user, store and timestamp)
* Maintain logical data integrity for patient at all sites 
  * At any particular time on any site, patient details to equal sum of all recorder changes 

The biggest challenge we have is concurrent editing in sync sites, in existing mSupply sites it's possible to overwrite changes since the whole patient record is sent when editing:

![F1CA6203-9E7E-417E-BC91-6DF097D283EF](https://user-images.githubusercontent.com/26194949/172280626-5e89f1b0-0cb8-4c0b-858a-6b833c1b5a5a.jpeg)

I would like to go over option 1 for both first (remote and central), and then add some comments (it's slightly refined from what I've suggested earlier, in this example there is no need for merging or parent relationship).

One things to keep in mind, we are not expecting mass edits of patient details or other associated data/documents, it's possible that quite a lot of new data/documents will be associated with a patient, but changes to patient details or associated document would be very rare.

## Option 1

* Every time `document` is edited, we just record the edit of what's change by whom and where.
* Current state of the document is all of the edits summed up (priority by edit time)
* When a document that is linked to actual database record (i.e. patient details) arrives at any particular site we recalculate the state of this document and update associated record (if changed).
* Patients only sync during initialisation/lookup, after that any changes happen via `document`

These four rules would be all that's needed, and implementation logic would be simple. 

There is one question, `how do we know what's changed without knowing the parent` ? The API to 'updateDocument' would require submitting previous version of document (diff is easily deduced, previous version is available since UI needs to display it when editing). Conflicts can be easily identified, just check previous version with current state (I don't think we need to worry about conflict at this stage, always. use the latest, since we record and can display full history)

![384D739E-1719-470F-83DB-7F8F16472CA7](https://user-images.githubusercontent.com/26194949/172285846-733cab6c-cd9c-4fc3-b489-dd21e826d3cf.png)

We wouldn't need to maintain parent relationship or hash things, and this addresses all of the requirements as far as I can tell.

4D code would be pretty simple and very little overhead, detailed pseudocode below:

```
for each synced document type of each patient
   
  does this document type update patient ? no -> continue

  get all documents for that type and that patient:
  
    sort them by timestamp

    new document state = {}
    for each document
      for each document field and value
         new document state [field] = value

    update patient if different from new document state
```

If we do by field change, I would rename document to document_log

## Comments and questions

> B tries to commit v_B but server detects that v1 , which v_b is based on, is
not the latest version anymore

how do we know if it's not the latest version anymore ? Get all documents that are not referenced as parents, if they don't match existing parents of document then it's not up to date ?

> The easiest approach is to do an implicit merge of all these heads when querying a document.

What does implicit mean in this context ? (I would assume it means `on the go` without persisting it, and `explicit` would mean `with persistence` and explicit would mean we need to maintain it from different triggers (sync and update via api)

> Note: is single site merge needed then?

I think if we can avoid merge all together that would be preferable, otherwise we need to maintain extra merge state and make sure it's always in sync.

> Every document change is recorded as a diff to the previous (latest) version, e.g.

In the example code after this line, there is `added` and `removed`, can we just set field value to null if it was removed ?

> lookup performance when applying many changes?

If this is true, it would apply to option 2 unless explicit merge happens. If explicit merge happens then this overhead is still there, just not at the time of query. Also the merge of option 2 is a lot more overhead (have to deduce ancestors, then deduce differences base, then merge vs just accumulating changes by timestamp).

> relies on storing diffs (less room for later optimizations)

I am not sure what this means, can you give an example ? I think it's would already be optimised.

> harder to apply custom merge strategies, e.g. if array merges are needed

I don't think this is accurate, if you want to diff more complex types in a more granular way you can still do it (i..e in the pseudocode above, at the time of `new document state [field] = value` you have full value of complex type just like you would for option 2.

> theoretically possible to start without common base

How is this possible in practice ?

> faster lookups and scalable (if having many changes to a single document)

This assumes there are many many changes for the document (haven't done any benchmarks, but would assume it's in the thousands), I wasn't aware that documents will be edited on mass scale ? (I could be wrong, was this concern raised previously raised ?). I would assume that mechanism git uses was design with this requirements, and thus some of the complexity is to accomodate it.

Also without explicit merge you still have to confirm that document is on latest version, which would require looking at non referenced parents (which would mean selecting all of the document, seeing what parents they have and they comparing those parents with all of the documents..). And with explicit merge, have to maintain and persist merged state in more than one trigger place, and recalculate this on re-sync.


> Cons:
> * more involved algorithms (see below)
+ bandwidth

> Common ancestor algo:

When doing the merge, diff needs to be deduces anyways, searching for common ancestors is only to deduce diff (so why not store it).

And git diff relies on order from ancestor for conflict resolution, not timestamp, which is what we want, see this example

If I understand our diagram correctly, I think it only looks at timestamps of the latest version ? Consider this example:

![599771E2-52E9-4580-B059-AEE8AFFF0F61](https://user-images.githubusercontent.com/26194949/172294348-6834ce3c-8234-4fac-a7b4-9e26237ac515.jpeg)


> For all these keys check if the corresponding field has been added, removed or modified in theirs / ours (relative to base)

Changes from base in theirs (ignoring v8 and v7):

```json
{
  "name": "Thomas Holmes"
  "dob": "03/01/2000"
}
```

Changes form base in our

```json
{
  "name": "Thomas"
  "ed": "Tertiary"
}
```

Since `ed` and `dob` are = `If mutation only happened in ours OR theirs` it's ok their new values look good

But `name` = `If mutation happened in ours AND theirs -> use solve strategy, e.g. "TakeChangeFromLatest" (ours in example) to resolve conflict`. So we take the value of the latest timestamp, which is actually `t = 7`, so we take value of `Thomas`, which was updated before (t = 3) current value of `Thomas Holmes` (t = 5). 
So to be correct, using the git modal (which relies on ancestor chain vs timestamp), we would need to do a diff of every parent to child (which makes the algorithm even more complex, and sounds a lot like storing diff modal).

> central server has to know how to merge

I think this is pretty simple considering pseudocode mentioned above

> performance problem?
> central server only needs to handle sync -> lower performance requirements

I think we need to bench this, or at least consider all possible scenarios (it will be rare that documents are actually edited, as far as I can tell).

Also on performance front, during initialisation central server needs to gather all of the records related to a patient, I think having an explicit relation on document to patient is important (so some sort of join table would be needed, or explicit patientId on document, I think the later is easier).

> For reporting, there is a special reporting site which receives all required data from the central server to do the reporting.

We used to have special sync site type for that reason (collector), which we've removed to simplify sync (it has to be special since the new site won't be able to edit the records, but we would need to sync them to this site). Also this new site would need to have full reporting functionality that existing mSupply central has, and I would assume sync overhead would be substantial).

So far we've been assuming that logical data integrity on central server is always maintained, i wonder if having duplicates breaks this assumption

## Extra

Wanted to spec out changes on mSupply central

We are trying to keep sync as simple as possible, proposed changes:

* Adding more related tables that sync with patient shouldn't be a problem (since this already happens for other related tables), as long as they have direct relation to patient

Patient Update

#### Option 1

* Processing and consolidating documents to update patient, is adding some complexity, if update code is simple it shouldn't be a big problem (since we will have post sync processing mechanism, which is triggered after sync and can do arbitrary operation on the synced records, like generating transfer)

#### Option 2

* We would need to change our sync mechanism to look up all `duplicates` of patient and pass along the documents to appropriate sites (during initialisation, lookup and normal sync operations)
* Patients are still stored in name table, and name.id (primary key) is still related to invoices, repeats, prescriptions (i think) etc.. @clemens-msupply how would this work ? What would we need to add to mSupply central ?

## Lastly

We need to spec out backward compatibility with existing sites, at least for patient details. Or run the issue past stakeholders (maybe it's ok to no be backwards compatible)

**Comment by clemens-msupply** [comment]
You need the parent relationship to reconstruct the exact previous version as the user has seen it. Its also very helpful to know what a user was seeing when editing a document.

**Comment by jmbrunskill** [comment]
**Option 3**

We could simplify the model and not try to merge records from different sites at all, instead we could always the latest record.

Assumption for this model is that concurrent edits one different sites are rare, in the case that they do occur by displaying  the latest one the result will not be catastrophic. 
By recording each version's single parent, we could detect a conflict and potentially warn the user to investigate the document history.

Each time a document is saved the full record is recorded as saved by the user, along with parent_version_id and timestamp, store_id and user_id. All non-sync'd versions of the document are sent to sites that don't have them.

When looking at a document, the latest version of the document will be used by default, but all versions of the document would be available from the database for traceback and allow the user to review changes from another site/user and manually apply those changes to a new version as required

Pros:

- Very simple option to implement
- Easy to understand for users and developers alike
- Reconstructing the document at the time of editing by a user would be possible (by recording parent_id)
- The system never displays a document that wasn't a version that a user saw

Cons:

- Merged records wouldn't be automatically created, if combined set of changes are required, a human would need to review the history and save a new version.
- Records can be dangling, and not part of a full tree
- Merkle Tree style validation of change history using hashes is not possible.

```
Andrei's Scenario

T=0
Store=1
Site=A
User=Alice
---------------
name: Tom
dob: 02/10/2000
ed: Secondary
---------------

T=3
Store=1
Site=A
User=Alice
---------------
name: Thomas
dob: 02/10/2000
ed: Secondary
---------------

T=5
Store=2
Site=B
User=Bob
---------------
name: Thomas Holmes
dob: 02/10/2000
ed: Secondary
---------------

T=6
Store=2
Site=B
User=Bob
---------------
name: Thomas Holmes
dob: 03/10/2000
ed: Secondary
---------------

T=7
Store=1
Site=A
User=Alice
---------------
name: Thomas
dob: 02/10/2000
ed: Tertiary
---------------

T=8 
SYNC
```

Resulting record from Option 1 (Applying Sequential Diffs)
```
---------------
name: Thomas Holmes
dob: 03/10/2000
ed: Tertiary
---------------
```

Resulting record from Option 2 (GIT Style Tree)
```
---------------
name: Thomas
dob: 03/10/2000
ed: Tertiary
---------------
```

Resulting record from Option 3 (Latest full record wins)
```
---------------
name: Thomas
dob: 02/10/2000
ed: Tertiary
---------------
```

In this scenario it looks like Option 1 would give the best result, but can we be sure this is the case for all document types and sets of changes?
If we display a version entered by a real user, we can be sure the system hasn't created any logical inconsistencies or incorrectly merged records?

Potentially if the document history isn't a straight line of parent records we could alert the user somehow to review the historical versions (Maybe we would need some way to clear this alert though as it could be annoying?)

**Comment by jmbrunskill** [comment]
Summary of Andrei's requirements against Option 3...

> Able to edit same patient details concurrently on different sync sites
>- Avoid changes to field A overwriting changes to field B  - **Potentially Compromised (if a change is applied before sync has occurred from a different site)**
>- Latest changes takes priority (i.e. concurrent change to the same field) - **Met**

> Able to enter arbitrary data for patient (and change it i.e. if mistakes were made or patient info has changed)
> - Aggregate type (one instance of form/data per patient i.e. patient details)
> - Tracker type (multiple instances of form/data per patient i.e. encounter)
> - Able to configure above form inputs and data shapes
> - Able to re-configure above form inputs and data shapes

**Unaffected**

> Record all changes for above by (user, store and timestamp) - **Met**
> Maintain logical data integrity for patient at all sites
> - At any particular time on any site, patient details to equal sum of all recorder changes - **Potentially Compromised (The latest version from whichever user last saved the record is displayed)** 

**Arguably logical integrity is well maintained in Option 3 as the data saved and displayed is always the result of a human action not a software process**

**Comment by andreievg** [comment]
I haven't fully digested the idea, but It's the simplest and it leaves pathways open for Option 1 and 2 (or I think any other, since base information is recorded).

**Comment by andreievg** [comment]
This is in the back of my mind, don't want it to go stale, my conclusion:

* Option 3 is simplest and allows transition to Option 1 and 2
* Option 3 captures the base data so it can accomodate any future requirements

One other requirement that I didn't put in the list is
* Record previous state when new state of document is created (Option 1 will need to record more info for this). And example of this is when prescription (B) is made, but there is a new state of document with another prescription (A) that hasn't synced yet, we should be able to store the state of document when (B) was made (i.e. that user wasn't aware of (A)). I think this requirement spans a bit further and can really complicate things (we also want to know the state of all other documents at the time document is created/edited), like a prescription may accompany an encounter, and encounter that is not synced yet may render prescription 'dangerous'. At this point we need to record synced timestamps : /

Another requirement that I haven't hear before but need to confirm

* Protect from mutability (i.e. someone having full access to database, I think we have huge problems if this is the case)

Actionables:
- [ ] Still need @clemens-msupply view on this
- [ ] Check requirements with stackeholders

If Option 3 is chosen (it looks like 2 out of 3 are in favour)
- [ ] Simplify (removing hashing, merging etc..)
- [ ] Get a really good sense of requirements and if Option 3 doesn't cut it, then collaborate to weigh in general requirements like maintainability/performance/scalability when deciding on a new option.

**Comment by clemens-msupply** [comment]
Lets just remove the merge and keep the hashing. Having the hashing allows us to keep our temper resistance claim. For example, by simply creating a merge document referring to all dangling heads and recording the hash of this merge document. This only needs to be done when recording a hash.

Yes we have a problem when somebody has DB access but its becomes an even bigger problem if you can't detect it.

We also need a logical clock (in the DB not in the data model), e.g. similar to a Lambert clock, to determine the latest edit. Otherwise, you could run into the problem that you seemingly can't update a document, e.g. because some site runs a few minutes fast.

**Comment by andreievg** [comment]
> Lets just remove the merge and keep the hashing. Having the hashing allows us to keep our temper resistance claim. For example, by simply creating a merge document referring to all dangling heads and recording the hash of this merge document. This only needs to be done when recording a hash.

I don't think Option 3 needs hashing or merging dangling heads, as for `our temper resistance claim` see below

> Yes we have a problem when somebody has DB access but its becomes an even bigger problem if you can't detect it.

We need to confirm that temper resistance (beyond API restrictions) is a requirement.

> We also need a logical clock (in the DB not in the data model), e.g. similar to a Lambert clock, to determine the latest edit. Otherwise, you could run into the problem that you seemingly can't update a document, e.g. because some site runs a few minutes fast.

As we've mentioned, concurrent updates on the same patient at different sites is super rare. Updates to patient data would be done when patient is visiting the clinic, and I don't think it's possible for patient to visit multiple clinics/sites within minutes. So personally I don't think it's a common enough issue to warrant a solution. 

I think it would be sufficient to send current datetime in sync headers and for central server to keep track of these and inform admin users (or us) if there is a big discrepancy.

**Comment by clemens-msupply** [comment]
Agreed solution: Option 3
Summary:
- When there was a concurrent edit the full latest edit wins (no automerge and previous edits are only preserved in the history)
- If there are two or more heads because of concurrent edits, a new edit should be based on the latest version
- Every edited document points to the parent the document is based on (to reconstruct the document state before and after the edit)
- This keeps the door open for future changes, e.g. auto merge or combined hash of all parents are still possible in the future

**Comment by andreievg** [comment]
Each sites upserts name record (patient) based on the latest document (including central server) whenever document type is inserted (triggered through sync or insert operation).

Need to check backwards compatibility (insert issue here)
* Using existing patient in just V5 sites (migration to document or creating of documents on next patient edit or..)
* Existing mSupply sites and documents ?

What to do with potential remote server time discrepancies (insert issue here)

**Comment by clemens-msupply** [comment]
Logical clock issue:
https://github.com/openmsupply/open-msupply/issues/123

**Comment by clemens-msupply** [comment]
This has been implemented now
