### ISSUE TITLE
[prog][control] Array of strings

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#932]
The array control looks weird when its an array of strings:

![Image](https://user-images.githubusercontent.com/88299195/207163198-383fb87c-5251-438f-9617-9437fcaaceb6.png)

@anisha-msupply Should we fix the existing one or maybe use a multi select component instead? like:

![Image](https://user-images.githubusercontent.com/88299195/207163478-983c0403-501e-4245-bbc2-34e32257c4e1.png)

**Comment by anisha-msupply** [comment]
> The array control looks weird when its an array of strings:
> 
> @anisha-msupply Should we fix the existing one or maybe use a multi select component instead? like: 


I think multi select would be best if entries are likely to be short (1-2 words?). Otherwise I'd suggest condensing the existing a bit - shift the field onto the same line as the number, which will likely remove the need arrows on the right and make it a bit cleaner. How important is it to have each one numbered?  
  
<img width="757" alt="image" src="https://user-images.githubusercontent.com/117775597/207430407-f619b065-0000-44c6-8249-4df147a0d639.png">

**Comment by clemens-msupply** [comment]
Think for a string list we don't need the numbering. (In general, no requirements for the numbering, just how we did it so far)

**Comment by roxy-dao** [comment]
New requirements in #1119, now a drop down list of medications
