### ISSUE TITLE
'Last sync' status says it happened 'tomorrow'

### ISSUE THREAD

**Issue by nisha-dangol** [openmsupply/open-msupply#989]
## Issue Description
Weird to see `tomorrow` in the **Last Sync** in Sync Status page. 

## Screenshots
![sync wrong msg](https://user-images.githubusercontent.com/59193490/210036448-cbfec516-ecb0-43c6-b45e-03051af255c2.png)

**Comment by mark-prins** [comment]
Something very strange with the date value being sent by the server

e.g. today at 12:00pm the site shows this:

<img width="541" alt="image" src="https://user-images.githubusercontent.com/9192912/217671133-cae67260-696a-49a7-b30e-57db2b954782.png">

while the server sends this:

```
"summary": {
                "__typename": "SyncStatusNode",
                "finished": "2023-02-08T12:55:27.717518+00:00",
                "started": "2023-02-08T12:55:26.362643+00:00"
            }
```

The local offset is 13h, which is why the `02:00` value is shown ( the date utils are rounding the value to the nearest 5 minutes )

**Comment by roxy-dao** [comment]
The times for last synced seems to be fine for me 🤔 

![Screen Shot 2023-02-14 at 1 38 02 PM](https://user-images.githubusercontent.com/61820074/218607946-ccdc7f10-353d-45a0-9424-b79d20e2f6e6.png)

**Comment by mark-prins** [comment]
the demo server had the time set incorrectly. Changed to the correct time and was unable to replicate after that.
Set the server to different time zone to the client and still working as expected.
